XamlControlsGallery/ControlPages/ComboBoxPage.xaml
Just noticed we are missing  `/` for the strings.
Currently they are `<x:String>Blue<x:String>`, which should be `<x:String>Blue</x:String>`
=> Fix ComboBox xaml sample

XamlControlsGallery/ControlPages/NavigationViewPage.xaml, XamlControlsGallery/ControlPages/NavigationViewPage.xaml.cs, XamlControlsGallery/ControlPages/RichEditBoxPage.xaml
Fixing two accessibility bugs pertaining to 200% text scaling and radio button invocation with Narrator.
- Added text wrapping property.
- Updated NavigationView options' RadioButtons to use more specific Checked events instead of more generic Click events.
- Bug 19597343: Text Scaling Desktop: XAML Controls Gallery : Information present for RichEditBox is clipped in 200% Text Scaling.
- Bug 19440518: Narrator Desktop : XAML Controls Gallery : Unable to change the position of navigation pane using caps+enter 
manual verification
=> Accessibility bugs

XamlControlsGallery/ControlPages/CompactSizingPage.xaml, XamlControlsGallery/ControlPages/ListViewPage.xaml, XamlControlsGallery/ControlPages/ToolTipPage.xaml, XamlControlsGallery/ControlPagesSampleCode/ListView/ListViewGroupedHeaderSample_xaml.txt, XamlControlsGallery/ControlPagesSampleCode/ListView/ListViewStickyHeaderSample_xaml.txt, XamlControlsGallery/XamlControlsGallery.csproj
This change fixes several syntax typos for sample markup related to incorrect closing tags. The fixed pages are ListView, ToolTip, CompactSizing.
Further fixes towards #14 
Manual testing
=> Fix several typos in markup samples (ListView, Compact Sizing, ToolTip)

XamlControlsGallery/ControlPages/RevealPage.xaml
CommandBar items were getting cut off in 200%+ text scaling.
Fixed the CommandBar to show the overflow button and to not have a fixed width so it will adapt better to text and window sizes.
Internal bug 19231991.
At 200% text scaling and maximum text scaling as well as min and max window widths. All appear to work as intended now.
=> Fix to text scaling and overflow on Reveal page

XamlControlsGallery/Common/LanguageList.cs, XamlControlsGallery/ControlPages/CalendarViewPage.xaml, XamlControlsGallery/ControlPages/CalendarViewPage.xaml.cs, XamlControlsGallery/XamlControlsGallery.csproj
Replaced free-form TextBox language entry with predefined language list available inside a (non-editable) ComboBox.
The predefined list of languages is copied from https://docs.microsoft.com/en-us/windows/uwp/publish/supported-languages. I chose to put English first with others in alphabetical order.
Fixed internal bug 19973652 by removing the need for error MessageDialog.
=> Update to CalandarView language UI 

XamlControlsGallery/ControlPages/SwipePage.xaml
Fixed the swipe control to actually display all info it can when the system text is scaled to 225%.
Just upped the width number. Didn't completely remove it because when I do, the swipe control expands the entire width of the window which looks super awkward when attempting to swipe it. It will show all the text necessary on the item at max 225% text scaling though with this fix.
Some text was being cut off when the text scaling was increased through the system.
Tested on min and max window widths and at min and max system text scaling options.
=> Swipe control text fixed at 225% scale text

XamlControlsGallery/ControlPages/DataGridPage.xaml
It appears that RichTextBlocks do not respond well to the Win+Backspace shortcut while in caret browsing mode. This combination frequently causes the Gallery app to crash. Replacing RichTextBlocks with TextBlocks appears to prevent the crash from occurring.
I'm not able to repro this problem reliably in a stand-alone test app.
Replaced the RichTextBlock on DataGrid page with two TextBlock controls.
Internal bug 20036436
Manually verified. Also compared before/after screenshots to make sure the change in controls did not result in any changes to layout visuals.
=> Updated DataGrid page to use TextBlock instead of RichTextBlock

XamlControlsGallery/ItemPage.xaml, XamlControlsGallery/ItemPage.xaml.cs, XamlControlsGallery/ItemsPageBase.cs
Removing custom focus logic, which I believe to be intended to improve gamepad navigation.
The primary ScrollViewer was inadvertently trapping focus, prevent users from being able to Tab pas the first element. This also resulted in Tab and Shift+Tab showing different behavior. Removing three private methods (Loaded, GotFocus, KeyDown) responsible for unpredictable keyboard behavior.
Also updated if statement in another private KeyDown method to use MUXC instead of WUXC NavigationViewItem, and added null check.
internal bug 19414657
Manually verified with keyboard and gamepad
=> Custom focus

XamlControlsGallery/ControlPages/CommandBarFlyoutPage.xaml, XamlControlsGallery/ControlPages/CommandBarFlyoutPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/CommandBarFlyout/CommandBarFlyoutSample1_cs.txt, XamlControlsGallery/ControlPagesSampleCode/CommandBarFlyout/CommandBarFlyoutSample1_xaml.txt
Updated CommandBarFlyout page to use a Button instead of Border and cleaned up associated events. 
Neither Border nor Image accept keyboard focus, so this page was broken for that input device. By placing the image inside a Button, I got focus and Click events for free. There is one difference from the previous version of this page - the Button's border no longer changes color when the CommandBarFlyout is open. I chose to omit that feature because it violated HC colors - hard-coding color values does not respect user theme preferences.
Internal bug 19244959
Rest:
Keyboard focus:
With CommandBarFlyout:
=> Updated Image on CommandBarFlyout page to be accessible with keyboard

XamlControlsGallery/ControlPages/TreeViewPage.xaml.cs
we should not reuse the same TreeViewNodes across multiple treeviews. This causes weird behavior during drag and drop because the nodes were raise events that both treeviews were messing with and changing state on the nodes.
When dragging and dropping, the dragged element is still in the previous location and the tree of nodes gets messed up. 
internal bug: https://microsoft.visualstudio.com/OS/_queries/edit/19973161/?triage=true
manually tested the treeview page and ensured that drag drop did not cause weird behavior.
=> Don't reuse treeview nodes across treeviews.

XamlControlsGallery/ControlPages/ComboBoxPage.xaml.cs
The original editable ComboBox logic had a bug when size = 8 because it was both inside the list of options but outside the range of 8-100 exclusive. 
The fix is to check if the value is in the list OR in the range of 8-100.
Fixes internal bug 20255162.
Manual testing on Editable ComboBox page.
N/A
=> Fix editable ComboBox page to stop crashing at size = 8

XamlControlsGallery/ControlPages/ListViewPage.xaml
This is how the ListView sample code looks like now:
```xml
<ListView ItemsSource="{x:Bind Contacts}"/>
<ListView.ItemsPanel/>
<ItemsPanelTemplate/>
<ItemsStackPanel AreStickyGroupHeadersEnabled="False"/>
<ItemsPanelTemplate />
<ListView.ItemsPanel/>
<ListView/>
```
It is obviously invalid XAML because all the tags are self closing, so I moved the slashes back where they belong:
```xml
<ListView ItemsSource="{x:Bind Contacts}">
<ListView.ItemsPanel>
<ItemsPanelTemplate>
<ItemsStackPanel AreStickyGroupHeadersEnabled="False"/>
</ItemsPanelTemplate >
</ListView.ItemsPanel>
</ListView>
```
=> Fixed ListView sample code

XamlControlsGallery/ControlPages/CommandBarFlyoutPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/CommandBarFlyout/CommandBarFlyoutSample1_cs.txt
Added check for whether pointer is over the button target to determine correct mode for CommandBarFlyout.
When invoked with keyboard, users must be able to navigate with keyboard within the CommandBarFlyout. When invoked with a pointer, users should see the more compact, transient CommandBarFlyout. Unfortunately, the Click and ContextRequested events don't have arguments detailing which input device was used to fire them. So I'm using pointer position (Buton's IsPointerOver property) as a proxy. Unfortunately this approach is not full-proof, nothing prevents users from moving their cursor over the button and pressing the Space key. But this seems better than always showing the expanded Standard flyout mode.
Internal bug 20144165
=> CommandBarFlyout's show modes

XamlControlsGallery/ControlPages/AutoSuggestBoxPage.xaml.cs
Fix a flicker in AutoSuggestBox when updating searches.
We were using ObservableCollection before, clearing the collection will close the suggestion list, adding new results into it will open the list again, which looks like a "flicker".
Creating a new list for each search now to avoid clearing the collection.
https://microsoft.visualstudio.com/OS/_workitems/edit/20495197
=> Fix AutoSuggestBox flicker

XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
Temporarily removing the app-wide search KeyboardAccelerator code.
The use of this keyboard accelerator is causing unexpected behavior on the search results page. After the shortcut is invoked, the Pivot control showing search results begins to trap the Tab key and prevents users from moving focus out of its headers. 
This fix removes the Ctrl+E keyboard accelerator, allowing us more time to investigate the problem and provide the correct solution. I have opened a new [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/20642466) to track this.
Internal bug 20594924
=> Remove Ctrl+E shortcut

XamlControlsGallery/ControlPages/AcrylicPage.xaml, XamlControlsGallery/ControlPages/AcrylicPage.xaml.cs, XamlControlsGallery/XamlControlsGallery.csproj
New 19H1 feature is the Acrylic luminosity - this PR is to add a small demo of that property to the Acrylic page.
Added a sections after the last sample on the Acrylic page with a tint opacity and luminosity opacity slider that updates the acrylic surface live to show you how the new luminosity property works in conjunction with the tint opacity property.
The main reason why the luminosity opacity property was introduced was to improve shadow performance by removing the need for the shadow to be "cut out" with the shape of the elevated surface. Luminosity when raise and in balance with the tint opacity can almost completely mask the color black from shapes that are behind the Acrylic surface.
- Multiple screens
- Min and max window sizes
- Min and max tint and luminosity values
- Light + …
=> Acrylic Luminosity Sample

XamlControlsGallery/ControlPages/InkCanvasPage.xaml
Previously, the InkCanvas was placed on a panel that had a hardcoded white background, which broke high contrast. The fix is to use a dynamically updating theme brush. 
Internal bug 19620306.
Manual verification
Before
After
=> Fix InkCanvas high contrast issue

XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml
Image URI on AnimatedVisualPlayer page was incorrect.
Fixes issue where AnimatedVisualPlayer's FallbackContent doesn't show static fallback image.
locally on 17763
=> Fix Image URI for AnimatedVisualPlayer.FallbackContent

XamlControlsGallery/App.xaml
Remove setting PlaceholderForeground explicitly in App.xaml.
There is a product bug 19027035 which can be partially blamed on the Control Gallery app since it is used by tester to generate that bug.
Part of the bug description: Hint text should be visible in the focused TextBox in dark theme.
Debugging the Control Gallery app, I realized PlaceholderForeground  property is set explicitly in App.xaml for TextBox and ComboBox style, and it is causing trouble for focused visual state. 
Internal bug 19027035 
##How Has This Been Tested?
Manually verified.
This is my first pull request for XAML Control Gallery , please let me know if I am missing anything.
=> Remove setting PlaceholderForeground explicitly in App.xaml.

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml, XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample3_cs.txt, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample3_xaml.txt
Updated the highlight colors and default focused/unfocused colors used by the "custom editor" sample on RichEditBoxPage.
When searching for a substring, the sample now draws with the user's accent color as the search highlight in light/dark theme, and with the text selection background color in HC. The foreground color also gets updated to complement the highlight background and remain legible. (Highlighting in yellow on dark theme, which draws text in white, was not legible.) The code also resets both background and foreground color when the search is cleared, ensuring appropriate colors for the theme and state (focused/unfocused) are drawn.
Internal bug 20388743
Manually verified in light, dark, and HC
=> Updated colors used by RichEditBox custom editor

XamlControlsGallery/ControlPages/StandardUICommandPage.xaml, XamlControlsGallery/ControlPages/StandardUICommandPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/StandardUICommand/StandardUICommandSample1_cs.txt, XamlControlsGallery/ControlPagesSampleCode/StandardUICommand/StandardUICommandSample1_xaml.txt
I added a workaround to enable proper context menu behavior, fixing and issue with invocation (Shift-F10, etc). Due to limitations in declaration of context menu's in markup with listview, the context menu for this sample is now created instead in code behind.
=> Fixing a bug with ContextMenuFlyout of the StandardUICommand sample.

XamlControlsGallery/ControlPages/MenuFlyoutPage.xaml
Adds a missing " that made the example code invalid
The example code did not compile
Has not been tested
=> Add missing quotation mark in MenuFlyout example

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample4_cs.txt
Our sample code was modifying the context menu but no the selection menu. As a result, users would see a different set of available commands depending on how they opened floatie.
Added Opening event code to SelectionFlyout in addition to ContextFlyout.
The sample now provides a consistent user experience. Before this fix, highlighting some text to select it would show a closed CommandBarFlyout without the custom "share" command.
Manually verified.
=> Updated RichEditBox's custom menu example

XamlControlsGallery/XamlControlsGallery.csproj
Retargets the project to the now-public 19H1 (18362) SDK and the latest WinUI 2.2 package.
I had to update the SDK since WinUI now requires it. If you're not ready to update the SDK for the project yet then you can leave this PR in limbo, but I offer it just so you know there's new goodness out there. :)
=> Retarget to 19h1 and WinUI 2.2

XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml.cs
The sample was trying to allow scrolling via keyboard when there is no focusable element in the content (i.e. its just an image).  It makes the ScrollViewer a tab stop since it isn't by default.  It was also handling keydown so that when it reaches the extent the keydown doesn't bubble up to the scrollviewer for the page and cause the content to continue to scroll down.  The bug is that the keydown handler was marking everything as handled.  What it should be doing is only handling the up/down.
=> Fix accessibility issue preventing tab navigation.

XamlControlsGallery/ControlPages/AcrylicPage.xaml
The Acrylic luminosity sample is causing crashes. This change collapses the sample so that it is not visible while we get to the bottom of the crash. 
#107 
Tested against x64/Release
=> Hide the Acrylic luminosity sample that is causing crashes.

XamlControlsGallery/ControlPages/MenuFlyoutPage.xaml
#112 highlighted an issue where the ToggleMenuFlyout sample looked strange because the flyout was reserving space for the checkmark, but it wasn't initially clear that the item was toggle'able. This change makes the ToggleMenuFlyout samples checked by default so it's clear why the space is needed.
#112 
Manual
Before:
After:
=> Clarify ToggleMenuFlyoutItem sample

XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
Ensured app title remains visible in all NavigationView modes and states.
Previously, the "XAML Controls Gallery" title of the app would be hidden whenever the primary NavigationView's pane was closed. As a result, when the gallery ran in a small window its app title would not be visible most of the time. This change keeps the title visible but moves it out of the way of the pane sliver when needed. The title moves to avoid overlapping the pane when appropriate, so I added an implicit animation to make the transition more visually appealing.
Also updated the vertical alignment of the title to look more centered relative to caption controls.
As a best practice, apps should have a visible title. When drawing into the window title bar, the burden to have a title falls on the app itself. The …
=> Updated state of app title

XamlControlsGallery/ControlPages/ColorPickerPage.xaml
Added More button to the sample.
Added a toggle to show the More/Less button built into the ColorPicker control.
We found an [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/22974472) where the hover state of the More button wasn't always correct. I wasn't able to verify whether this was an issue with the common Xaml control because the Gallery didn't show the More button. 
Manually verified.
=> More button in ColorPicker page

XamlControlsGallery/ControlPages/CheckBoxPage.xaml
Changed wrong content attribute in code sample to reflect the actual component
Changed the Content attribute of the second Checkbox sample from "Two-state Checkbox" to "Three-state checkbox"
This was changed since the component being described by the code sample is actually a three state checkbox and not a two state checkbox.
Fixes https://github.com/microsoft/Xaml-Controls-Gallery/issues/93
Tested manually by starting the project.
=> Change code sample to be fit the component it is for

XamlControlsGallery/ControlPages/StandardUICommandPage.xaml.cs
Fixed a bug where the context menu in the StandardUICommandPage would not delete the item when it was not selected.
Made the menu flyout automatically select the component it is being created for. By doing that, the item in the list is being selected and the deletion of the item will work. In addition to that it is clear to which component the context menu belongs.
Closes #106.
=> Change StandardUICommandPage to select the item it is for; Closes #106;

XamlControlsGallery/ControlPages/ImplicitTransitionPage.xaml.cs
Fixed a bug where the application would crash if input was not sanitized. Also added flyouts if the input is out of range and fixed the code relating to registering enter key in TextBox.
Added a Flyout that gets rendered when either: 
- the input is not a number 
- the input is not in range for the respective transition attribute/element 
This was done by surrounding the parsing with try/catch blocks and adding else cases to the if cases that check if the input is in range. In case of "failure" a method gets called that creates a Flyout for the respective textbox.
The registering of the enter key was fixed by using the actual header text of the TextBoxes (the wrong header was expected thus the checks failed).
Fixes #3
=> Fix bug where app crashes when input was invalid; Fix bug where enter key was not registered in TextBox; Closes #3;

XamlControlsGallery/ControlPages/AutoSuggestBoxPage.xaml.cs, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs, XamlControlsGallery/SearchResultsPage.xaml.cs
Improved the search to be more inclusive. See #96 for more info.
Tokenized the query by splitting it using the character " " (whitespace) and accept queries/items if they contain every token of the query. 
For example the query "split button" generates the tokens "split" and "button" so every item that contains both "split" and "button" will be accepted (unlike before where "splitbutton" was rejected)
Fixes #96.
Tested manually by starting application and entering queries that have been rejected before (e.g. "split button").
=> Improve search to be more inclusive; Closes #96;

XamlControlsGallery/ItemPage.xaml.cs
Fixed a "bug" where the OnNavigatedFrom event of the ControlPages were not being called.
I added a call to the OnNavigatedFrom method from the Pages manually in the ItemPage.xaml.cs file. 
This change/fix is a bit more complex since the OnNavigatedFrom method is not being called because the hierarchical structure of the Page/XAML is not layed out in a way that would trigger the method on the ControlPage.
Oversimplified diagram of controls nesting:
```
<App>
<NavigationRootPage>
<ItemPage> <---- "Root" page / "source of frame"
<-ControlSamplePage- /> <--------- Not the root page / "source of frame"
</ItemPage>
</NavigationRootPage>
</App>
```
Since the individual control pages are not the source of frame, OnNavigatedFrom will not be called (at least according to …
=> Fix "bug" where OnNavigatedFrom was not called; Closes #74;

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml, XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs, XamlControlsGallery/ControlPages/SplitButtonPage.xaml, XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs
Fixed a bug where color was not applied to the typed text when the users changes position in the RichEditBox.
Fixed the bug by saving the last saved color and reapply anytime the user types
Fixes #139.
Tested manually by starting application. 
Tested adding text, clicking to random position in text and typing text.
=> Fix coloring behaviour with RichEditBox; Closes #139;

XamlControlsGallery/ItemPage.xaml.cs, XamlControlsGallery/PageHeader.xaml.cs
Added self made unload event for PageHeader to register if the ItemPage gets unloaded. See #75 for use case.
Added a public method in PageHeader that will be called when the ItemPage gets unloaded.
This was done to register when the PageHeader "gets unloaded". The unload event of the PageHeader does not get triggered since it is actually not being uploaded as it is part of the NavigationRootPage and not part of the ItemPages. See following diagram:
```
<App>
<NavigationRootPage>
<PageHeader /> <---- The PageHeader in which we want to notice the unloading
<ItemPage> <---- Page which gets unloaded
<-ControlSamplePage- /> 
</ItemPage>
</NavigationRootPage>
</App>
```
Helps with/fixes #75;
Test by manually starting application.
Added breakpoints in the `Event_ItemPage_Unloaded` function to …
=> Add "unload" event method in PageHeader for Itempage unload; Closes #75;

XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
Made app focus the searchbar (AutoSuggestBox) at app start.
Changed the function OnNewControlsMenuItemLoaded to instead of focusing the "New page" tab to focus the searchbar.
Closes #109.
=> Focus searchbar onstart

XamlControlsGallery/App.xaml.cs, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
Fixed a bug with the appearance of the caption controls which would sometimes be white with white background/black with black background.
Improved the logic which is used to detect the current theme and moved the changing of the color to the Loaded event of the root page, since only when the app is loaded the "real" theme is determined and not the requested/user theme.
Fixes #142 .
Tested manually by running steps in issue #142.
=> Fix bug with appearance of caption controls; Closes #142;

XamlControlsGallery/ControlPages/GridViewPage.xaml
Fixed bug where navigating to the next image in the gridview would take two key activations.
Removed containing grid of the image and added AssessibilityView="Raw"
Fixes #168.
Tested manually by navigating through grid with narrator enabled in item mode.
=> Fix bug with narrator not switching item at first try; Closes #168;

XamlControlsGallery/ControlPages/ToggleSplitButtonPage.xaml, XamlControlsGallery/ControlPages/ToggleSplitButtonPage.xaml.cs
Fixed bug where ToggleSplitButton could not be activated on touch displays.
Removed the "Click" event and replaced it with "IsCheckedChanged" event.
Fixes #166.
Tested manually by starting XCG in windows simulator with touch enabled and tripple tapped button. Also tested behavior with cursor.
=> Fix bug with togglesplitbutton and touch displays; Closes #166

XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml
Fixed bug where the first ScrollViewer in the "ScrollViewer (preview)" page was not focusable.
Added a ' IsTabStop="True" ' to the ScrollViewer.
Fixes #160.
Tested by tabbing through page.
=> Fix bug where first ScrollViewer was not focusable; Closes #160;

XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml.cs
Fixed a bug where zoomslider would jump around and not stay in the position it should be.
Added a check if the user actually is zooming with the mouse by detecting mouse over.
Fixes #182.
Tested following scenarios:
- Zooming with mouse over scrollviewer
- Focus on zoomslider, Zooming with mouse over scrollviewer
- Zooming using zoomslider
=> Fix bug where zoomslider would jump when sliding; Closes #182;

XamlControlsGallery/ControlPages/PullToRefreshPage.xaml.cs
Fixed problematic icon color when using high contrast mode in the PullToRelease component.
Added a check wether:
* High contrast mode is enabled
* The high contrast mode is one of the following:
* "High Contrast #1"
* "High Contrast #2"
* "High Contrast White"
Fixes #158.
Tested manually by going through all themes and contrast modes and check if color of icon is suitable.
=> Fix sun icon wrong color on high contrast in PTR page;

XamlControlsGallery/ControlPages/GridViewPage.xaml.cs
Fixed misleading click message output for GridView item click
Casted the sender component into its correct class and accessed the title that way to generate a user readable output
Fixes #187
Tested manually by repeating steps in issue
=> Fix misleading click message output; Closes #187;

XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml
Fixed a bug where navigating with narrator would not allow focusing of scrollviewer with image
Added "AutomationProperties.Name" property
Fixes #181 .
Tested by navigating through page with narrator and press shift tab to get to the scrollviewer.
=> Fix bug where narrator would not shift-tab to scrollviewer; Closes #181;

XamlControlsGallery/ControlPages/AppBarButtonPage.xaml, XamlControlsGallery/ControlPages/AppBarToggleButtonPage.xaml, XamlControlsGallery/ControlPages/ButtonPage.xaml, XamlControlsGallery/ControlPages/RepeatButtonPage.xaml, XamlControlsGallery/ControlPages/RepeatButtonPage.xaml.cs, XamlControlsGallery/ControlPages/ToggleButtonPage.xaml, XamlControlsGallery/ControlPages/ToggleButtonPage.xaml.cs
Added samples to component pages which have a RevealStyle which is not enabled by default (e.g. Button)
Added code samples to components
Goal is to add the Reveal styles to the component where they are available for and show them on their sample page so users won't miss them. This PR is an effort towards #155.
Tested manually by navigating through component pages and checking if Reveal style is displayed in a fashion that it is comprehensible for the user.
=> Add Reveal styles (and Accent style) to samples

XamlControlsGallery/XamlControlsGallery.csproj
Fixed the displaying of PullToRefreshPage.xaml(.cs) in project view
"Moved" the PullToRefreshPage.xaml.cs inside PullToRefreshPage.xaml file in project view
Makes project view a bit more cleaner
Tested manually by starting Visual Studio and the XCG application.
Changed this:
into this:
=> Move PullToRefresh.xaml.cs inside its .xaml file in project view

XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Update WinUI package to 2.2 release and remove experimental scrollviewer2 sample. (The code is still there but not compiled)
Updates to the latest 2.2 release package. Since the release package does not contain preview features (like ScrollViewer2) removed that sample from the compile step and from the landing page. 
This step is required before updating the Gallery to include the release version of TabView & other 2.2 features. 
Clean rebuild, manual verification across several pages.
=> Update WinUI package to 2.2 release

XamlControlsGallery/ControlPages/SplitButtonPage.xaml, XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs
Fix a bug where hitting control+b and similar commands will result in navigating the app with focus becoming nearly impossible
Changed the event that was used since the previous event for text colorization would create an endless loop.
I also added the code that was introduced to the RichEditBox in #157 so that the same behavior does not occur in the SplitButton sample.
Closes #200
Tested manually by starting application, visiting the RichEditBox on the SplitButton page and hitting control+b. After that I was able to successfully navigate to other commands using tab navigation.
=> Fix bug with changing focus and apply changes from #157 to SplitButton page, Closes #200

XamlControlsGallery/ControlPages/AcrylicPage.xaml, XamlControlsGallery/ControlPages/AcrylicPage.xaml.cs
Fix the problem with the acrylic sample page crashing. Reenabled the TintLuminosityOpacity sample for Windows 10 Build 18362 users.
The problem for the crashing was that we casted an Microsoft.UI.Xaml.Media.AcrylicBrush to Windows.UI.Xaml.Media.AcrylicBrush which failed and crashed the app.
Closes #107 
Tested manually by starting application and navigating to Acrylic page.
=> Fix crashing with acrylic page, Closes #107

XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs, XamlControlsGallery/XamlControlsGallery.csproj
Updated the WinUI package to the latest release.
Removed a small fixed for NavigationView, that is not needed anymore as it was fixed with latest version.
Updated the WinUI package to be able to samples for the new RevealStyles.
Removed a small fix to clean code base a bit.
Since a bug with the TeachingTip was fixed with the latest WinUI package version, would it be better for TeachingTip samples to not add the TeachingTip to the PageHeader (which I assume was needed because otherwise TeachingTips were not closing upon navigating away). Instead we could add the TeachingTips to targets in the sample and by that have the sample code be a bit more explanatory.
@stmoy and @YuliKl What are your opinions on that?
=> Updated nuget version, remove fix for now fixed bug

XamlControlsGallery/DataModel/ControlInfoData.json
Fixed the image link for the AnimatedVisualPlayer page, which was also needed the MediaPlayerElement page.
Fixes #211 
Tested manually by starting application and navigating to MediaPlayeElement page.
=> Fix bug where app would crash when opening MediaPlayerElement page

XamlControlsGallery/ControlPages/TabViewPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/TabView/TabViewKeyboardAcceleratorSample_cs.txt
The TabView page uses KeyboardAccelerators to add/remove tabs via CTRL+T, CTRL+W. If we don't mark them as handled, they will occasionally "double fire" and open/close two tabs at a time. Since we are handling the event, we should mark the event as handled. 
Fixes an internal bug.
Manual.
=> TabView: Mark handled keyboard accelerator events as handled

XamlControlsGallery/ControlPages/InkCanvasPage.xaml, XamlControlsGallery/ControlPages/InkCanvasPage.xaml.cs
Replaced toggle switch for pen tip with radio buttons.
Fixes #219 
Tested manually by navigating to InkCanvas page and testing if both pen tip options work correctly.
=> Switch from ToggleSwitch to radio buttons for pen tip in InkCanvas page

XamlControlsGallery/ControlPages/SliderPage.xaml
I added the height property, setting it to 90 for the vertical slider, effectively increasing the height of it.
The issue is that there was not really any range for the vertical slider to be moved
https://github.com/microsoft/Xaml-Controls-Gallery/issues/232
Building the app on x86, Windows 10 1903 Build 18362. 10024
No other code was effected.
Looks like this now:
used to look like:
=> Fixing issue 232

XamlControlsGallery/ItemTemplates.xaml
Just changed the width of the grid for the user control in ItemTemplates.xaml
345 * 1.25 = 431.25, which is not a whole number, therefore it will round the pixel down. Therefore not true scaling of 125%
To make scaling better
Build and resized the window. It is one pixel different so can't really see it, but mathematically it will work since 344 * 1.25 = 430.
Still can fit controls horizontally two in a small window since the width was reduced
=> 344 is a better value since it scales well

XamlControlsGallery/DataModel/ControlInfoData.json
There was a missing full stop for the MenuBar description
Added a fullstop to the ControlInfoData.json file
Consistency with grammar.
Building the project
before:
after:
=> added full stop for MenuBar description

XamlControlsGallery/DataModel/ControlInfoData.json
Added full stop for splitbutton subtitle and description
Missing full stops 
Consistent grammar
Shouldn't fail, I couldn't build the project for some other reason
=> added full stop to subtitle and description

XamlControlsGallery/App.xaml.cs, XamlControlsGallery/Behaviors/ImageScrollBehavior.cs, XamlControlsGallery/Common/ThemeHelper.cs, XamlControlsGallery/ControlExample.xaml.cs, XamlControlsGallery/ControlPages/PullToRefreshPage.xaml.cs, XamlControlsGallery/ItemPage.xaml.cs, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs, XamlControlsGallery/SettingsPage.xaml.cs, XamlControlsGallery/XamlControlsGallery.csproj
Refactored code related to theme saving and storing into a separate file `ThemeHelper` to make the handling of that easier and make future changes in that area easier. Now themes are stored there and not in the App class.
Also added a listener to system wide color (and thus theme) changes so we can update the system caption buttons when the user updates the theme system wide.
Remove redundant code, improve maintainability slightly. Also fixes #251 
Tested following scenarios:
- Switch from dark/light to light/dark (in App)
- Switch from use system to dark/light
- Switch from dark/light to use system settings
- Switch system theme while using the option "use system settings"
=> Fix system caption buttons not updating colors when system theme changes

XamlControlsGallery/ControlPages/RevealFocusPage.xaml, XamlControlsGallery/ControlPages/RevealFocusPage.xaml.cs
Added substitution that updates when we change the focus visual kind
Fixes #253
Tested manually by starting application and changing the reveal mode.
=> Fix bug where focus reveal kind sample would not update

XamlControlsGallery/PageHeader.xaml
66 doesn't scale well, 66 * 1.25 = 82.5, therefore it rounds. 68 doesn't need to round when scaled, since 68*1.25 = 85
Improve scaling
Building
=> changed MinHeight of headerRoot to 68

XamlControlsGallery/ItemPage.xaml
Changed the width of the content frame so that it is wide enough for wide content code snippets
Scrolling vertically can be interrupted by a horizontal scroll in the code snippet when the users mouse enters the vicinity of the code snippet area. I have changed the width for WideFrameContent ever so slightly so that there is no longer a need to scroll horizontally. At least as tested on the Tab View page. This also removes the difficulty of reading code that barely doesn't fit, and requires the user to scroll horizontally to see the content on the Tab View page, and other pages hopefully as well.
Code snippets can sometimes be a bit to wide to fit on the page, so to see all of it you have to scroll horizontally, I wanted to remove the need for that, so it's easier to read by the user. When …
=> Width of code snippet expanded to remove horizontal scrolling

XamlControlsGallery/ControlPages/ProgressBarPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Updated the existing progress bar sample to use the new WinUI version of the control.
- Moved the app to latest WinUI preview version
- Changed the namespace used in progress bar sample
- Marked progress bar page as "preview" until we switch to a release version of WinUI
New-to-WinUI control
manually verified
=> ProgressBar update

UITests/base.cs, XamlControlsGallery/ControlPages/TreeViewPage.xaml, XamlControlsGallery/Debug.appxmanifest, XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs, XamlControlsGallery/XamlControlsGallery.csproj
Fixes #275 
Added Debug.appxmanifest where the app's display name and package name are different ("XAML Controls Gallery (Debug)", and changed the code so that the title is pulled from the package configuration instead of hard-coded in XAML.
Also fixed an error I kept seeing where some TreeView page elements were using Name instead of x:Name and the compiler complained.
=> Enable Debug builds to run side-by-side with store version

XamlControlsGallery/ControlPages/PageTransitionPage.xaml
The PageTransition "Drill" would result in the C# code sample displaying the "DrillNavigationTransitionInfo" which does not exist. Instead it should be "DrillInNavigationTransitionInfo"
Fixes sample code issue
=> Fix misspelled page transition DrillInNavigation

XamlControlsGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample4_xaml.txt
Fixed typo "BackButtonVisibility" to "IsBackButtonVisible".
BTW: Why is "IsBackButtonVisible" a Visibility and not a boolean? Seems a bit counter intuitive to me. 😅
Fixes #283 
Tested manually by starting app and navigating to NavigationView page.
=> Fix typo with backbutton visibility in NavigationView sample

XamlControlsGallery/ControlPages/TabViewPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
Fixes #282 
The complete TabView sample includes a complete sample that shows how to make TabView go into the titlebar, rearrange tabs, and pull tabs into their own window. The underlying tech for the last sample is AppWindow, which is only available on 18362+.
This change adds a warning to the sample and disables the TabView tear out behavior. 
Manual testing on a 17763 VM
=> Disable AppWindow part of TabView sample on old versions of Win10

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs, XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample3_cs.txt
Fixed bug #286 by detecting when user has changed text upon REB gaining focus, to not interfere with that.
Fixes #286 
Tested by reproducing steps in #286:
1. Launch XAML Control Gallery app.
2. Navigate to "SplitButton" or "RichEditBox" in All controls and activate it.
3. In the textbox (or last sample of RichEditBox page), select the text written and right click to invoke the context menu and select "Cut" menu item.
4. Again invoke the context menu and activate "Paste" menu item and observe.
=> Fix bug where cut and paste would not correctly work on SplitButtonPage and RichEditBoxPage

XamlControlsGallery/ControlPages/CommandBarPage.xaml
in CommandBar sample, re-ordered buttons so Share in corner.
Should use the OS icon for Share when we labeled the button 'Share', moved it over too so it's near the menu.
=> Should use Share icon for Share button

XamlControlsGallery/ControlPages/GridViewPage.xaml
Fixed the bug described in issue #327 where GridViewItems don't show up in a screenreader/Accessibility Insights with a descriptive name. 
Tested with AccessibilityInsights for Desktop to make sure that item names were appearing and were descriptive (bound to their Title property).
- [ x ] Bug fix (non-breaking change which fixes an issue)
=> Fixed bug in Issue #327 - GridView Accessibility

XamlControlsGallery/XamlControlsGallery.csproj
Updating the WinUI package to the latest 2.4 pre-release. Release notes can be found [here](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0-prerelease.200203002).
=> Update to use latest WinUI 2.4 pre-release pacakge

XamlControlsGallery/ControlPages/InkToolbarPage.xaml.cs
Apparently "Rectangle" is not a valid value for pencil's, thus simply changing the PenTip value, when the user selected pencil through the InkToolBar.
#333
Tested by reproducing steps in issue.
=> Fix app crash when trying to set pencil to rectangle on inktoolbar page

XamlControlsGallery/ControlPages/ListViewPage.xaml.cs
The message boxes in the Inverted ListView for Messaging or Data Logging sample were hard to read in both light and dark mode, so I changed the color to make them more distinct and readable. This was done after feedback from @pag3 that his screen made it really difficult to read the text in the message boxes with the current colors and contrast.
Tested locally on my machine and different monitors in both light and dark mode.
=> Patch - ListView Page: Changed color of message box for visibility

XamlControlsGallery/ControlPages/ProgressBarPage.xaml, XamlControlsGallery/ControlPages/ProgressBarPage.xaml.cs
Add manual handling of NumberBox value change, instead of using binding. It seems like the ProgressBar page is the only page where we are using a binding,
Fixes #353 
Tested manually by reproducing steps in issue:
1. Launch XAML Controls Gallery.
2. Activate ProgressBar from All Controls Page.
3. Click on text box present under header A determinate Progress bar, clear the value of text box and then either press context menu key or right click with mouse and observe.
=> Fix crash with NumberBox value being NaN

XamlControlsGallery/ControlPages/ComboBoxPage.xaml
Increase width of ComboBox to account for text scaling >= 200% and prevent clipped text.
Fixes #354
Tested manually with text scaling 225% (see screenshot)
=> Increase ComboBox width to account for text scaling

XamlControlsGallery/.editorconfig, XamlControlsGallery/Common/NavigationHelper.cs, XamlControlsGallery/Common/ObservableDictionary.cs, XamlControlsGallery/Common/RelayCommand.cs, XamlControlsGallery/Common/SuspensionManager.cs, XamlControlsGallery/ControlPages/CalendarViewPage.xaml.cs, XamlControlsGallery/ControlPages/CommandBarPage.xaml.cs, XamlControlsGallery/ControlPages/TreeViewPage.xaml.cs, XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
This PR resolves all violations of the following rules:
- IDE0018: Variable declaration can be inlined
- IDE1005: Delegate invocation can be simplified
Recommendation:
> `out` variables should be declared inline when possible.
Rationale: https://styleascode.net/ID/IDE0018
Instances resolved: 6
---
Recommendation:
> The null-conditional operator should be used to simplify delegate invocation when possible.
Rationale: https://styleascode.net/ID/IDE1005
Instances resolved: 7
See #331.
Tests were not run. Solution does compile & run without errors.
=> Resolves 13 code style rule violations.

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml
Changing the color of the text in the animated scrolling ItemsRepeater sample so that it's always black, and visible despite being on dark or light mode. 
Fixing issue #360.
Tested in light and dark mode on my machine.
Light mode:
Dark mode:
=> Fixing dark mode issue

XamlControlsGallery/Common/VariedImageSizeLayout.cs, XamlControlsGallery/ControlExample.xaml.cs, XamlControlsGallery/ControlPages/AppBarButtonPage.xaml.cs, XamlControlsGallery/ControlPages/AppBarPage.xaml.cs, XamlControlsGallery/ControlPages/AppBarSeparatorPage.xaml.cs, XamlControlsGallery/ControlPages/AppBarToggleButtonPage.xaml.cs, XamlControlsGallery/ControlPages/ComboBoxPage.xaml.cs, XamlControlsGallery/ControlPages/CommandBarFlyoutPage.xaml.cs, XamlControlsGallery/ControlPages/CommandBarPage.xaml.cs, XamlControlsGallery/ControlPages/DataGridPage.xaml.cs, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs, XamlControlsGallery/ControlPages/NumberBoxPage.xaml.cs, XamlControlsGallery/ControlPages/ProgressBarPage.xaml, XamlControlsGallery/ControlPages/PullToRefreshPage.xaml.cs, XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs, XamlControlsGallery/ControlPages/TabViewPage.xaml.cs, XamlControlsGallery/SamplePages/SamplePage2.xaml.cs
This PR resolves all violations of the following rules:
- IDE0017: Use object initializers
- IDE0028: Use collection initializers
Two new violations of rules IDE0018 & IDE1005 were resolved.
Two spelling mistake regressions were also reapplied.
Recommendation:
> Both object and collection initializers should be used, regardless of how many elements are being set.
Rationale: https://styleascode.net/ID/IDE0017
Instances resolved: 20
Recommendation:
> Both object and collection initializers should be used, regardless of how many elements are being set.
Rationale: https://styleascode.net/ID/IDE0028
Instances resolved: 3
See #331 & #363.
Tests were not run. Solution does compile & run without errors.
=> Resolves 25 code style rule violations.

XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
Fix the missing Toggle Theme button. We were looking up the PageHeader in the tree and caching it. However, there are multiple PageHeaders - one in RootPage, NewControls and AllControls pages. Depending on the timing, we could end up caching the wrong one and never update it which caused us to be toggling visibility on the wrong page. Removing the cache and always getting the one in the tree fixes the issue.
=> Fix missing Toggle Theme button

XamlControlsGallery/ControlExample.xaml, XamlControlsGallery/ItemPage.xaml, XamlControlsGallery/ItemPage.xaml.cs, XamlControlsGallery/ItemsPageBase.cs
This change removes several competing animations when the user navigates between pages. This change removes the connected animations between the GridView and each page, the custom animations on **each individual sample** and updates the page navigation transition to use DrillIn, which is consistent with the [animation guidance](https://docs.microsoft.com/en-us/windows/uwp/design/motion/page-transitions). 
Fixes #423 
Manual testing.
**Before**:
**After**:
=> Clean up page navigation animations

XamlControlsGallery/ControlExample.xaml.cs
This PR fixes leftover whitespace characters at the end of individual lines within multiline samples.
Having leftover whitespaces makes the UX worse when copy-pasting samples into other projects to try them out, as you need to manually check line by line whether the code has unwanted characters.
- From code, by testing the generated `string` before/after the new logic added in this PR.
- In the app, by highlighting and copy/pasting various code samples with this issue.
**Before:**
**After:**
=> Fixed stray whitespaces in multiline code samples

XamlControlsGallery/ItemPage.xaml
The RowSpan was set to 3, resulting in the overlap. Without that, the RelatedControls section does not overlaps with the feedback section.
Fixes #444 , Fixes #450 , Fixes #451 
Before:
After:
=> Fix issue with the related controls section overlapping

XamlControlsGallery/ControlPages/RadioButtonPage.xaml
Add `VerticalScrollBarVibility=Hidden` to hide the scrollbars.
Closes #455 
=> Hide unused scrollbars in RadioButtonsPage

XamlControlsGallery/ControlPages/RadioButtonPage.xaml
As the title says. Instead of using the checked property of the individual RadioButton items, we use selectedIndex.
Fixes #445 
@stmoy @ranjeshj Should the is checked work in that scenario or is it expected that it didn't work previously (to this PR)? Could this be an issue with the RadioButtons control?
=> Fix bug where the first radiobutton wouldn't be checked on page start

XamlControlsGallery/ControlPagesSampleCode/Brushes/RadialGradientBrushSample_xaml.txt
The current API of RadialGradientBrush is RadiusX and RadiusY. The sample however says that RadiusX is a point, which would cause compiler errors.
Keep sample up to date.
=> Fix faulty RadialGradientBrush sample code

XamlControlsGallery/XamlControlsGallery.csproj
Updating WinUI version to latest [2.5 prerelease](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.5.0-prerelease.200609001)
=> Update WinUI version to 2.5 prerelease

XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml, XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml.cs
This improves the AnimatedVisual player demo
Closes #441 
Tested the following scenarios:
- Play->Pause->Play->Pause
- Play->Stop->Play
- Play->Reverse->Pause->Play
- Play->Reverse (wait for end)->Play
- Play->Reverse -> Stop -> Play
=> Improve animated visual player demo

XamlControlsGallery/ControlPages/ImplicitTransitionPage.xaml.cs
The page crashed when setting the opacity and other values in samples on the page since a cleared NumberBox will report double.NaN as its value which is not a valid value for those cases. This is now fixed by wrapping the "get call" and setting the NumberBox value to 0 if its NaN.
Fixes #475 
Tested manually by clearing the NumberBox values and clicking the "set value buttons" on the samples.
=> Prevent crashes on ImplicitAnimation page by checking for NaN

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml
Add theme resource override to highligh buttons in high contrast correctly
Fixes #461
Tested manually:
=> Add override for ButtonBackgroundPointerOver in high contrast

XamlControlsGallery/ControlPages/ConnectedAnimationPage.xaml
The sample crashed as on a freshly loaded page, the selecteditem of the RadioButtons was null. By setting SelectedIndex in XAML, the RadioButtons now always know the selected item, and thus fixing the crash.
Closes #494 
Opened ConnectedAnimationPage and pressed the "Navigate" button. App did not crash.
=> Fix issue with ConnectedAnimation crashing due to selection being null

XamlControlsGallery/ControlPages/RadioButtonPage.xaml, XamlControlsGallery/ControlPages/RadioButtonPage.xaml.cs, XamlControlsGallery/ControlPages/RadioButtonsPage.xaml, XamlControlsGallery/ControlPages/RadioButtonsPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
This PR splits the RadioButton page into a sample for the RadioButton control and a sample for the RadioButtons control
Closes #490
=> RadioButtons page

XamlControlsGallery/ControlPages/ScrollViewerPage.xaml
User could not use Ctrl +/- to zoom in and out of the ScrollViewer in the ScrollViewer sample page.
Arrows, PageUp, PageDown, etc did not work either to scroll its Image. The IsTabStop=True setting allows the control to take focus & keyboard input works now.
This is for internal bug 26337703 - Cannot set focus to ScrollViewer.
Ad-hoc testing of the ScrollViewer sample page.
=> Allowing keyboard input for the ScrollViewer

XamlControlsGallery/NewControlsPage.xaml.cs
Add a ToString override which gets used by GridView/Accessibility Insights to provide an appropriate UIA name.
Fixes #326 
Tested with accessibility insights
=> Fix issue with groups not having appropriate UIA name

XamlControlsGallery/ControlPages/ListViewPage.xaml.cs
When loading the page, we set the focus to the first listview, resulting in the first item of that listview to be selected.
Closes #332 
Tested manually by opening page and checking which item is focused.
=> Set focus on first listview on ListView page when page loads

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml, XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs, XamlControlsGallery/ControlPages/SplitButtonPage.xaml, XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample3_cs.txt, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample3_xaml.txt
A few changes:
- Remove code that reapplied rtf when switching focus
- Switch default color from black to gray
I am not happy with the default foreground being gray, however this is the easy approach to fix the issue with black text on black background in dark theme. Having those depend on the current theme will make the samples definitely more complex, that is why I opted out of doing this for now.
Update samples as the recent changes to the RichEditBox control broke them.
=> Update samples that use the RichEditBox

XamlControlsGallery/DataModel/ControlInfoData.json
The WebView2 team recently published an official guidelines doc for using WebView2 with WinUI 3, so I'm updating a bunch of WinUI resources/docs to point to this new article. Changed the "Guidelines" link on the WebView2 page for the preview branch. 
WebView2 guidelines link was outdated.
Just opened the app and tested if the link opens to the right page.
=> Updating link for WebView2 page

XamlControlsGallery/ControlPages/ButtonPage.xaml
Update content of button to be "Accent style button", which let's narrator announce "Accent style button, button".
Fixes #554
Navigated through Button page with narrator
=> Button page: Fix issue with Narrator only announcing "Button" instead of content and control type

XamlControlsGallery/ControlPagesSampleCode/TreeView/TreeViewTemplateSelectorSample_xaml.txt
The example "A TreeView with ItemTemplateSelector" contains a typo in its `ExplorerItemTemplateSelector`:
The value of the property `x:key` was `ExpolrerItemTemplateSelector` and I changed it to `ExplorerItemTemplateSelector`.
This change solves a typo.
No test required
=> Fixed typo in TreeView sample

XamlControlsGallery/ControlPages/MenuBarPage.xaml
Changes have been made to the `MenuBarPage` sample to provide unique identifiable names to the `MenuBar` elements to make it easier to interact with them in automated UI tests.
Looking to build a wrapper element for the `MenuBar` WinUI control in the [Legerity UI test framework](https://github.com/MADE-Apps/legerity/issues/6) but finding the correct `MenuBar` to interact with is difficult due to there being no automation ID on the controls. 
Tested the change by inspecting the UI automation tree to ensure the Automation ID property is set to the name of the control.
- N/A
=> Added names to menu bars so they can easily be identified in UI tests

XamlControlsGallery/ControlPages/ButtonPage.xaml
This adds a sample to the button page showing how to handle large text inside buttons.
Closes #508 
=> Add button wrapping sample

XamlControlsGallery/DataModel/ControlInfoData.json
The description text on how to use the `TimePicker` control shows the following wrong text:
> Use a TimePicker to let users set a time in your app, for example to set a reminder. The TimePicker displays three controls for **month, day, and** and AM/PM.
It seems to be an oversight when copying the same description from the `DateTime` control description.
This fixes a minor help text issue that may confuse new users of the app.
Untested since it's a wording change.
=> Fixed incorrect wording in description of TimePicker control

XamlControlsGallery/ControlPages/ProgressRingPage.xaml, XamlControlsGallery/ControlPages/ProgressRingPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json
Added determinate mode example to the progress ring page. 
Added an example of how to set the IsIndeterminate property to change the progress ring in to a determinate mode progress ring that fills based on the value property. 
Ran on my local machine using the 2.5 pre-release package. 
New feature
=> Added determinate mode for progress ring

XamlControlsGallery/ControlExample.xaml
Adds LabeledBy property to TextBox to provide accessible name to padding textbox:
Closes #609 
=> Add UIA name to TextBox for padding in screenshot mode

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml
Set the value of `VerticalScrollBarVisibility` of the ScrollViewer containing the ItemsRepeater to `Auto` to hide the scrollbars when not needed.
Fixes #615
=> Auto-hide scrollbars in first ItemsRepeater sample if not needed.

XamlControlsGallery/AllControlsPage.xaml, XamlControlsGallery/App.xaml, XamlControlsGallery/ControlExample.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/NewControlsPage.xaml, XamlControlsGallery/PageHeader.xaml
The app was showing a few high contrast colors that were muddying up the accuracy of the control's appearance. To make Xaml controls show a more accurate representation of themselves, made the following two changes.
- Changed HighContrastAdjustment to None. 
Before:
After: 
- Updated controls examples to stop drawing ButtonFace color.
After:
Manually verified in regular and high contrast.
=> HC changes so controls look more accurate

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/ControlPagesSampleCode/ItemsRepeater/ItemsRepeaterNestedSample_xaml.txt
Adding horizontal scrolling to "Laying out nested ItemsRepeater" sample.
Fixes #580 
Manually verified with 100%, 200%, and resized window.
=> Horizontal scrolling in ItemsRepeater sample

XamlControlsGallery/ControlExample.xaml.cs
DependencyProperty Registration with the wrong name as Parameter
There is a DependencyProperty Registration with the wrong Name. 
This was causing some crashes due to a Name being registered multiple times.
Running the App and making sure this change does not break other areas
=> Fix DependencyProperty registration

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs, XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs
The issue was that setting the foreground is very expensive, however changing it to the value it already is doesn't have any benefit for us.
Through performance debugger, I found out that we spend 60% of CPU time on these two lines when resizing the window. By adding this check, resizing the window now works as expected again.
Fixes #529 
Tested through resizing page and looking at perf log.
=> Fix issue with resizing having horrible performance

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml.cs
When integrating with the latest WinUI, the sender is Microsoft::UI::Xaml::TextCommandBarFlyout other than Windows::UI::Xaml::CommandBarFlyout
It blocked the CommandBarFlyout pop up
=> Make the RichEditBox to be able to use Microsoft::UI::Xaml::CommandBarFlyout

XamlControlsGallery/Directory.Build.props, XamlControlsGallery/XamlControlsGallery.DesktopWap.Package.wapproj, XamlControlsGallery/XamlControlsGallery.DesktopWap.csproj, XamlControlsGallery/standalone.props
This updates XamlControlsGallery to target the Reunion 0.5.5 servicing release.
=> Updating XamlControlsGallery to Reunion 0.5.5

XamlControlsGallery/ControlPages/RevealFocusPage.xaml, XamlControlsGallery/ControlPages/RevealFocusPage.xaml.cs
This PR improves the a11y by providing a lot more descriptive UIA name for the color picker buttons.
In addition to this, we are also cleaning up some obsolete comments.
Closes #584 
=> Improve reveal focus a11y, remove obsolete comments

XamlControlsGallery/Debug.appxmanifest, XamlControlsGallery/Package.appxmanifest, XamlControlsGallery/XamlControlsGallery.csproj
There isn't an SDK for Windows 11 yet but we have tested the app on Windows 11 so set the MaxTestedVersion = 22200 so we get the latest behavior. We can remove/undo this when the SDK is available.
=> Update MaxTestedVersion to >= Windows 11

XamlControlsGallery/PageHeader.xaml
very minor fix.
Increases the height of commandBarBorder from 40px to 44px to prevent cut off, and increases the pageTitle grid to 44px to match commandBarBorder. 
Closes #739
manually.
=> Increase height of page command bar to prevent cutoff

XamlControlsGallery/SettingsPage.xaml
Makes the version number text selectable to make it easier to copy-paste somewhere else, like the issue template.
It can be a bit annoying to have to manually copy the version number, having it selectable is more convenient.
manually
=> Make version number text in settings selectable

XamlControlsGallery/ControlPages/ListViewPage.xaml.cs
Modified the "ListViews with Drag, Drop, and Reordering Support" sample to make it more generalizable from the specific setup in this app. Also increased clarity in comments, and removed a typo.
Modified the Drop handler for the "ListViews with Drag, Drop, and Reordering Support" sample's two ListViews. The insertion index is now initialized to zero. Only if there are items in the target ListView, does the calculation of the insertion index proceed. Otherwise the calculation is skipped and the index retains its initial value of zero. Also updated the comments to remove some ambiguity in describing what the code is doing. Finally, corrected a typo by removing an excess semicolon at the end of what was line 174 (now is line 170).
Previous version assumed height of ListViewItems in both …
=> Update ListView Drop handler to be more generalizable

XamlControlsGallery/ControlPages/ToolTipPage.xaml
Minor correction of the XAML Markup in the Tooltip examples.
The previous markup, which used invalid XML tags, was:
```XAML
<ToolTipService.ToolTip/>
<ToolTip Content="Offset ToolTip." VerticalOffset="-80"/>
</ToolTipService.ToolTip/>
```
n/a
=> correct source code examples of tooltip

XamlControlsGallery/ControlPagesSampleCode/TeachingTip/TeachingTipSample1_xaml.txt
This change replaces `controls` XAML namespace with `muxc` to refer `Microsoft::UI::Xaml::Controls`. It also removes trailing spaces and tabs.
This change fixes #691. The current example uses both `controls` and `muxc` to refer the same namespace. It's confusing.
I built and ran XamlControlsGallery (Debug x64) project using Visual Studio Enterprise 2019 Version 16.9.4 on Windows 10 Version 20H2 (OS Build 19042.985). I confirmed the first example was updated.
=> Replace controls XAML namespace in TeachingTip example with muxc

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs
The issue was that selecteditem was null when processing the layout selection change causing a nullreference exception
Closes #811
=> [ItemsRepeater page] Fix crash on layout selection

XamlControlsGallery/ControlPages/TreeViewPage.xaml.cs
This PR removes the `IsSelected` property, on a sample view model on the TreeView page. This was unused code before.
At least to me, the property strongly implies that it might be used with TreeView to bind to the `IsSelected` property of the TreeViewItem. This however, [does not work](https://github.com/microsoft/microsoft-ui-xaml/issues/125). So I think this is a bad sample property and should be removed.
See description above
Tested manually, app still builds, runs and TreeView page still works.
none
=> Remove misleading, unused property "IsSelected" in TreeView sample

XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
In the NavigationRootPage.xaml file the NavigationView Opening event had a misspelled name "_PaneOpened" instead of "_PaneOpening".
The spelling mistake did not apparently cause any issue. But during the development of my own app, I was referring to the code from XAML Controls Gallery app and found out that this name spelling mistake caused confusion and I was not triggering the right event which wasted time.
The change has been tested locally on the computer. It does not break anything.
Testing Environment: Windows 11 22000. 
It does not affect any other areas of code. It was just a event spelling mistake not referenced by any other code.
=> Fixed NavigationView PaneOpening Event Name

XamlControlsGallery/ControlPages/SplitButtonPage.xaml, XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs
Fix a bug where the items in the split button drop down were not keyboard invokable, which was (inappropriately) being flagged as a sev 1 accessibility issue for Winui.
=> Fix splitbutton keyboard accessability.

XamlControlsGallery/ControlPages/InfoBadgePage.xaml.cs
The navview sample would try to reopen the pane when switching to left compact which created rendering artifacts. Since switching to left compact and opening the pane does not look any different than left expanded, I've updated the code to leave the pane open.
Closes #843 
=> Fix issue with compact NavView InfoBadge sample

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml
Dash is on the wrong end of the closing tag. Only affects the displayed example code. XAML was correct in the functional code.
`
<ScrollViewer HorizontalScrollBarVisibility="Auto" 
HorizontalScrollMode="Auto" 
IsVerticalScrollChainingEnabled="False"
MaxHeight="500">
<muxc:ItemsRepeater
ItemsSource="{x:Bind BarItems}"
Layout="{StaticResource $(Layout)}"
ItemTemplate="{StaticResource $(ElementGenerator)}" />
<ScrollViewer/>`
Dash is in the wrong end of closing tag
When implementing the example in the readers code, they would copy and paste this example, which results in invalid XAML.
The change was required to make code functional and valid XAML. Tested the code in my own app.
I did not run any official tests, but this is not functional code for the application, rather just a text content …
=> Syntax typo in XAML example text in ItemsRepeaterPage.xaml

XamlControlsGallery/XamlControlsGallery.csproj
A new winui prerelease has been published, updating XCG to use it.
=> Update winui version to 2.8.0-prerelease.220118001

XamlControlsGallery/Controls/ControlExample.xaml, XamlControlsGallery/Controls/SampleCodePresenter.xaml, XamlControlsGallery/Controls/SampleCodePresenter.xaml.cs
Add expander around the sample code of the controls.
=> Add expander for sample code of control examples

XamlControlsGallery/ItemTemplates.xaml
The brush we were using was using an not optimal value in high contrast. Instead we are using the brush it is based on in non high contrast which also has a good fallback value in high contrast.
Closes #849
=> Fix issue for markers on whats new page in high contrast

XamlControlsGallery/ControlPages/TextBoxPage.xaml
=> Update TextBoxPage.xaml to fix color contrast ratio 

XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
The NavigationRootPage currently uses the ItemInvoked event, while we have moved to SelectionChanged in our internal version.  This change gets the two versions in sync.
Parity between XCG 2 and XCG 3
Manual testing
=> Change ItemInvoked->SelectionChanged on NavigationRootPage

XamlControlsGallery/ControlPages/AcrylicPage.xaml, XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml, XamlControlsGallery/ControlPages/RichTextBlockPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json
WInUI3 uses different links to samples and documentation.  This change updates the links to the correct WinUI3 ones.
Going to the right place is good.
Go to the links
=> Update URIs to correct links

XamlControlsGallery/ConnectedAnimationPages/CardPage.xaml, XamlControlsGallery/ConnectedAnimationPages/CardPage.xaml.cs, XamlControlsGallery/ConnectedAnimationPages/CollectionPage.xaml.cs, XamlControlsGallery/ConnectedAnimationPages/DetailedInfoPage.xaml, XamlControlsGallery/ConnectedAnimationPages/DetailedInfoPage.xaml.cs, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs, XamlControlsGallery/ItemsPageBase.cs, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs, XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
Fixing a handful of accessibility issues in the app.
Fixes the following issues
Internal: [Bug 37700602](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/37700602): [XCG]ItemsRepeater does not meet contrast requirements in Aquatic High Contrast theme
Images after the fix in Normal and Aquatic themes.
Internal [Bug 38293529](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/38293529): [XCG] WinUI Accessibility->Connected Animation card: When any item is invoked, KB focus does not fall on the immediate interactive control(Go back button)
Setting focus on the correct item after the connected animation.
Internal [Bug 37020621](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/37020621): [XCG] WinUI 3 Controls …
=> Fixing a few a11y issues in the app

XamlControlsGallery/ControlPages/CommandBarFlyoutPage.xaml.cs
Always be transient or not for a type of interaction. Switching it based on pointer over can be confusing for keyboard/narrator users.
Internal bug: [Bug 38293416](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/38293416): [XCG WinUI3] WinUI Accessibility->CommandBarFlyout card: See more menu list is expanding automatically when image is invoked.
=> Remove the transient vs not behavior based on pointer over in CommandBarFlyout page. Can introduce confusion to narrator users

XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
When there is only one tab left in the TabView Windowing sample, tearing it outside of window crashes app. This is because it still closes and opens a new window when on the last tab, but an error is thrown during .Close() as you can't close the only tab in the window. 
Simply disabling `CanReorderTabs` and `CanDragTabs` when `TabItems.Count == 1` suffices.
Fixes internal bug: 38125264
=> Fix TabView Sample Tear Behaviour Bug

XamlControlsGallery/Common/FileLoader.cs, XamlControlsGallery/Common/SuspensionManager.cs, XamlControlsGallery/Controls/ControlExample.xaml.cs, XamlControlsGallery/Directory.Build.targets, XamlControlsGallery/Helper/NavigationOrientationHelper.cs, XamlControlsGallery/Helper/ProtocolActivationClipboardHelper.cs, XamlControlsGallery/Helper/ThemeHelper.cs, XamlControlsGallery/Helper/UIHelper.cs, XamlControlsGallery/Package.MSIX.appxmanifest, XamlControlsGallery/Package.Universal.appxmanifest, XamlControlsGallery/Properties/PublishProfiles/win10-arm64-unpackaged.pubxml, XamlControlsGallery/Properties/PublishProfiles/win10-arm64.pubxml, XamlControlsGallery/Properties/PublishProfiles/win10-x64-unpackaged.pubxml, XamlControlsGallery/Properties/PublishProfiles/win10-x64.pubxml, XamlControlsGallery/Properties/PublishProfiles/win10-x86-unpackaged.pubxml, XamlControlsGallery/XamlControlsGallery.DesktopWap.Package.wapproj, XamlControlsGallery/XamlControlsGallery.DesktopWap.csproj, XamlControlsGallery/net6.override.targets, XamlControlsGallery/standalone.props
The ApplicationData.Current API is unavailable to apps without a package identity and this was causing unpackaged XamlControlsGallery to crash on launch due to usage of the aforementioned API in XCG 2.6. This change addresses that by replacing all usage sites of ApplicationData.Current with approximations when XCG is running without a package identity:
- [AppContext.BaseDirectory](https://www.hanselman.com/blog/how-do-i-find-which-directory-my-net-core-console-application-was-started-in-or-is-running-from)  as a replacement for ApplicationData.Current.LocalFolder
- Private static fields instead of persisting values to ApplicationData.Current.LocalSettings).
XCG does use other APIs that do not work without a package identity (e.g. Windows.ApplicationModel.Package) but they do not result in …
=> Fixes to run XCG unpackaged

XamlControlsGallery/App.xaml, XamlControlsGallery/TabViewPages/MyTabContentControl.xaml, XamlControlsGallery/TabViewPages/MyTabContentControl.xaml.cs, XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml, XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
The TabView sample that showed using TabView as a titlebar and allowing tabs to be torn out into a new window was not working for WinUI3 since it only worked for UWP. This updates the sample for WinUI3.
=> Fixes for TabView Windowing sample

XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.DesktopWap.csproj
The AnimatedVisualPlayer sample was disabled because the required Win2D component was not available at the time for WinUI3. The [Microsoft.Graphics.Win2D](https://www.nuget.org/packages/Microsoft.Graphics.Win2D) nuget package is available and supports what we need.
=> Re-enable AnimatedVisualPlayer sample

XamlControlsGallery/App.xaml.cs, XamlControlsGallery/ItemPage.xaml.cs, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
Selecting a search result directly from the dropdown off the AutoSuggestBox crashes the app because NavigationRootPage has a couple places which call Navigate() with the wrong parameter type. This is now fixed. I also saw some crashes in ItemPage.OnNavigatedFrom() due to the NavigationRootPage.GetForElement(this) returning null sometimes when the element isn't in a tree, so I've added a null check around those uses.
This also removes direct access to RootFrame for better encapsulation.
Crashes are bad
=> Fix search crash and crashes when the element root is null

XamlControlsGallery/ContentIncludes.props, XamlControlsGallery/Helper/NavigationOrientationHelper.cs, XamlControlsGallery/Helper/ProtocolActivationClipboardHelper.cs, XamlControlsGallery/Helper/ThemeHelper.cs, XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml, XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs, XamlControlsGallery/XamlControlsGallery.DesktopWap.csproj
In TabViewWindowingSamplePage.xaml.cs, ApplicationView is not found, so the full name is used (Windows.UI.ViewManagement)
NavigationOrientationHelper.cs(23,29): warning CS0414: The field 'NavigationOrientationHelper._isLeftMode' is assigned but its value is never used:
- The variable is only used inside an ifdef - move the declaration inside an ifdef
ProtocolActivationClipboardHelper.cs(16,29): warning CS0414: The field 'ProtocolActivationClipboardHelper._showCopyLinkTeachingTip' is assigned but its value is never used
- The variable is only used inside an ifdef - move the declaration inside an ifdef
ThemeHelper.cs(108,17): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the …
=> Fix build warnings and UNIVERSAL build break

XamlControlsGallery/ConnectedAnimationPages/CardPage.xaml, XamlControlsGallery/ConnectedAnimationPages/CollectionPage.xaml.cs, XamlControlsGallery/ConnectedAnimationPages/DetailedInfoPage.xaml, XamlControlsGallery/ConnectedAnimationPages/DetailedInfoPage.xaml.cs, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs, XamlControlsGallery/ItemsPageBase.cs
This PR ports the changes from #895 into the WinUI 3 version of the app.
@ranjeshj FYI since you authored the PR, @bpulliam FYI for WinUI 3
=> Port Pull request #895 (a11y fixes)

XamlControlsGallery/App.xaml, XamlControlsGallery/ItemPage.xaml.cs
- This fixes an additional case similar to #920) where GetForElement can be null.
- It also fixes a markup bug where a brush was specified instead of a color
=> Additional crash fixes

XamlControlsGallery/ItemPage.xaml.cs
The generated URIs pointed to the WinUI 2 branch (master), not the WinUI3 branch.
=> Fix Xaml source URIs to point to winui3 branch

XamlControlsGallery/ContentIncludes.props, XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml, XamlControlsGallery/ControlPages/ImplicitTransitionPage.xaml, XamlControlsGallery/XamlControlsGallery.DesktopWap.csproj, XamlControlsGallery/standalone.props
- Add LottieLogo1.png
- Fix the background to AnimatedVisualPage
- Update Win2D to version 1.0.3.1 (which now supports Hybrid CRT)
- Set the WinAppSDK minimum version to 1.0.3 (for Hybrid CRT & CsWinRT)
- Remove a hard-coded version in the project file
bonus fix:
- Also fix the background in ImplicitTransitionPage
=> Fixes for AnimatedVisualPlayer

XamlControlsGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample1.txt, XamlControlsGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample2.txt, XamlControlsGallery/SamplePages/SampleSystemBackdropsWindow.xaml, XamlControlsGallery/SamplePages/SampleSystemBackdropsWindow.xaml.cs
This change adds an ActualThemeChanged listener to the Mica/SystemBackdrops page in WinUI Controls Gallery. This allows the backdrop to update according to the theme without the user having to change the background.
(Cherry-pick from internal repo)
=> CP Update Mica backdrop when theme changes

XamlControlsGallery/Controls/ControlExample.xaml, XamlControlsGallery/Controls/ControlExample.xaml.cs, XamlControlsGallery/Controls/SampleCodePresenter.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
The ExtendsContentIntoTitleBar API is not supported in UWP.
Fix the GridLength and Thickness constructors for UWP.
Whitespace
=> fix universal breaks and whitespace

WinUIGallery/AllControlsPage.xaml, WinUIGallery/NewControlsPage.xaml, WinUIGallery/WinUIGallery.DesktopWap.csproj
Due to a bug in the proj file, the version of Win2D was not being set causing a break.
ALso add automation ids to the AllControls and NewControls pages.
=> Fix the publish step

README.md
In the readme there is a link to the pre-built version of WinUI Gallery on the Windows Store. Previously this pointed to `WinUI 2 Gallery` app, this update points it to `WinUI 3 Gallery` app.
Gallery update was posted to Twitter by Miguel Ramos. Someone in the comments asked if this is on the Windows Store and I said yes and got the link from the repo. Gosh is there egg on my face when the user says 
> The link prompts WinUI 2 install, not WinUI 3, is that?
I went to the link and it displayed the correct store page.
=> Updated link in README to point to WinUI3 Gallery on Windows Store

WinUIGallery/Debug.appxmanifest, WinUIGallery/Helper/ProtocolActivationClipboardHelper.cs, WinUIGallery/ItemTemplates.xaml, WinUIGallery/Package.appxmanifest, WinUIGallery/WinUIGallery.csproj
- also fixed bug with infobadge
=> Store Update 

WinUIGallery/ControlPages/TitlebarPage.xaml.cs, WinUIGallery/Helper/TitlebarHelper.cs, WinUIGallery/SettingsPage.xaml.cs
Title bar buttons are set to Black when in Light mode and vice versa for dark mode
=> Fixed titlebar buttons when changing theme

WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/Package.WAP.Debug.appxmanifest, WinUIGallery/Package.WAP.Dev.appxmanifest, WinUIGallery/WinUIGallery.DesktopWap.Package.wapproj
Similar to the WinUI 2 gallery, this PR adds a debug manifest that allows you to have the Store version and the development versions installed at the same time instead of the two versions overriding each other all the time.
Question: Right now the app would still display WinUI 3 Gallery when being started, is that good?
=> Add debug manifest file for development

WinUIGallery/ControlPages/AnimatedIconPage.xaml
Adds Automation Property Name to button with AnimatedIcon example.
Before:
After:
Internal bug: 40234408
=> AnimatedIcon: add missing automation name to button

WinUIGallery/Controls/HeaderTile.xaml
Fixes missing Automation Property Name in Header Tiles.
Before:
After:
Internal bug: 40233956
=> Adds Automation Name to HeaderTile

WinUIGallery/ControlPages/ButtonPage.xaml, WinUIGallery/ControlPages/CheckBoxPage.xaml, WinUIGallery/ControlPages/CheckBoxPage.xaml.cs, WinUIGallery/ControlPages/RevealFocusPage.xaml, WinUIGallery/ControlPages/SliderPage.xaml, WinUIGallery/ControlPages/SplitButtonPage.xaml
Removes the control type from the automation name, so narrator doesn't read repetitive and confusing information.
Fixes issue where two Elements of same control type had same automation name.
Fixes internal bug 40234538 and 40234974
=> Remove LocalizedControlType from Elements Automation Name

WinUIGallery/ControlPages/SplitViewPage.xaml.cs, WinUIGallery/Helper/WindowHelper.cs, WinUIGallery/IdleSynchronizer.cs
Move the WindowHelper into the helper directory, where it logically belongs.
Matching an internal code-cleanup change.
=> move window helper into helper directory

WinUIGallery/App.xaml.cs, WinUIGallery/ControlPages/TitleBarPage.xaml.cs, WinUIGallery/Helper/TitleBarHelper.cs, WinUIGallery/Helper/WindowHelper.cs, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/SettingsPage.xaml.cs
Since the origin of WinUI controls gallery is single window, many items like StartupWindow which tells the window information are static and don't work in multi window scenario. Instead, we should call xamlroot to find window object as well as app titlebar object when app content has finished loading
Also made a change where dropdown color in Titlebar page changes app titlebar uielement's color instead of titlebar container color. So that it would be painting it below the text instead of over the text.
Fix the issue where changes to the Window titlebar were applied to the wrong window.
Manual testing
=> Use the proper Window in multi-window scenarios

WinUIGallery/ItemsPageBase.cs
Pass options and set searchroot in FindNextElement, as required by the API
#1086
=> Fix crash due to invalid parameters to FindNextElement

WinUIGallery/ControlPages/TitleBarPage.xaml, WinUIGallery/ControlPages/TitleBarPage.xaml.cs
The issue was that Buttons inside a GridView are not entirely accessible, we are now using the same way as on the SplitButton page to solve this problem. This PR also cleans up some dead code/empty spaces.
Fixes #1071 
=> Fix issue with color selection on TitleBar page not being keyboard accessible

WinUIGallery/app.manifest
We are using WS_EX_LAYERED for the drag area of the title bar and it is created as a child window.
When a compability section is left out of the manifest, CreateWindow cannot create a child window with that attribute and the result is that you cannot drag using the title bar. The GUID used here is for Windows 10.
Adding this section to the manifest of your app will fix the issue.
This fixes the issue where the WinUI custom titlebar is not draggable.
Manual testing
=> Enable downlevel dragging of custom titlebar by adding Win 10 compatibility to the app manifest

WinUIGallery/App.xaml, WinUIGallery/Properties/PublishProfiles/win10-arm64-unpackaged.pubxml, WinUIGallery/Properties/PublishProfiles/win10-arm64.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x64-unpackaged.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x64.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x86-unpackaged.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x86.pubxml, WinUIGallery/SamplePages/SampleSystemBackdropsWindow.xaml.cs, WinUIGallery/WinUIGallery.DesktopWap.Package.wapproj, WinUIGallery/WinUIGallery.DesktopWap.csproj, WinUIGallery/standalone.props
There are signifcant changes in the WInAppSDK 1.2 release and this feature branch is the place to make necessary code changes to the WinUI Gallery to allow it to run on 1.2-preview2 (and eventually the stabel release).  When the stable release arrives, this branch will be merged into main, so this branch is temporary.
This change points to the 1.2-preview2 release and updates to CsWinRT 2.0.  That change does require VS 2022 and .Net 6.
Prepare for the upcoming release and give everyone a chance to give it a spin.
Manual Testing
=> Prepare for WinAppSDK 1.2

WinUIGallery/ControlPages/ListViewPage.xaml.cs
Thank you for WinUI-Gallery help, I was using it and found a typo and would like to send a PR.
`heigh => height` in `ListViewPage.xaml.cs`
=> fix: typo in ListViewPage.xaml.cs

WinUIGallery/ControlPages/SwipeControlPage.xaml
Changes:
- Update Delete from E107 to E74D
- Update Accept from E10B to E8FB
- Update Flag from E129 to E7C1
- In sample 4, fixed the Lock (was using Permissions instead) to E72E
- Fixed the sample code to match actual markup
As mentioned in microsoft/microsoft-ui-xaml#7850, there is a note in the documentation to use Unicode points E700+ when referencing glyphs.  This change only changes the specific references in the WinUI Gallery code itself.
=> Update Gallery glyphs to current standard

WinUIGallery/ControlPages/ScrollViewerPage.xaml
Changed the zoom value in the ScrollViewer page from 1 to 2.
This was required because scrolling features in the page were not visible due to the zoom placed on the image. The zoom needed to be at a higher value (<=2) in order to see the scrolling features.
=> Changed the zoom value to 2

WinUIGallery/ControlPages/WebView2Page.xaml
Add the Xaml source section
#1084
=> Add xaml source to webview2 page

WinUIGallery/ControlPages/ScrollViewerPage.xaml, WinUIGallery/ControlPages/ScrollViewerPage.xaml.cs
Updated the scroll viewer starting zoom to be 2.0 so when users select the control it is more clear what the scroll viewer does. Also renamed the x:name for the scrollviewer form `Control1` to `ScrollViewerControl` to make the name more meaningful.
This is a PR to fix issue #121. I picked this because it was the only issue marked as `good first issue` and was a relatively easy fix.
I believe this issue is isolated to the scroll viewer page. If there are tests that need updated I can do this.
=> Scroll viewer zoom to 2.0 on startup and rename control x:Name

WinUIGallery/ControlPages/SliderPage.xaml
This is a cherry-pick of change #831 from winui2.
It also removes the muxc namespace (not required in WinUI3) and fix UIA names.
Improvement to the page
Manual
=> Update Slider page

WinUIGallery/ControlPages/BreadcrumbBarPage.xaml, WinUIGallery/ControlPages/BreadcrumbBarPage.xaml.cs
Added the C# sample code to the samples, updated the second sample to show navigation behavior.
Closes #1000
=> Update BreadcrumbBar samples

WinUIGallery/ControlPages/TreeViewPage.xaml.cs, WinUIGallery/WinUIGallery.DesktopWap.Package.wapproj, WinUIGallery/standalone.props, nuget.config
Update WinAppSDK version to 1.2.2
Update Build Tools version
Adds standard nuget.config
Fixes #1120 
Removes unneeded mux prefix
General cleanup
=> General Hygiene fixes

WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample2.txt
As title
You don't need the mica controller when creating an acrylic window.
=> Remove unnecessary mica controller in source

WinUIGallery/Common/VariedImageSizeLayout.cs
Fix a crash when resizing the ItemsRepeater page to small width. 
The issue was that one of the custom layouts was getting to state where we would end up with no columns. The fix is to always have at least one column of items.
Fixes #1162
=> fix repeater page crash when resizing to a small width

WinUIGallery/ControlPages/RadialGradientBrushPage.xaml.cs
Keyboard arrow on radial gradient brush page looks broken because the steps are too small.
=> fix keyboarding in radial gradient page

WinUIGallery/ControlPages/RadialGradientBrushPage.xaml.cs
With #1168, the keyboard behavior was fixed for absolute mapping mode, however switching back to RelativeToBoundingBox now left that keyboard behavior in a broken state.
=> Fix RadialGradientBrush keyboard behavior

WinUIGallery/ControlPages/ProgressRingPage.xaml, WinUIGallery/ControlPages/ProgressRingPage.xaml.cs
=> Added the Background property to the ProgressRing page

WinUIGallery/ControlPages/AutomationPropertiesPage.xaml, WinUIGallery/NewControlsPage.xaml, WinUIGallery/SamplePages/SampleSystemBackdropsWindow.xaml, WinUIGallery/SettingsPage.xaml, WinUIGallery/SettingsPage.xaml.cs
Fixes the following:
Changes Theme on the settings page to use radiobuttons
Removes Automation Name from System Backdrops field so Narrator will use Content
Restores LabeledBy in actual Xaml that was still present in sample text
Adds Level to NewControls Groups
=> Accessibility fixes from internal repo

WinUIGallery/Directory.Build.props, WinUIGallery/Directory.Build.targets, WinUIGallery/WinUIGallery.DesktopWap.Package.wapproj, WinUIGallery/WinUIGallery.DesktopWap.csproj, WinUIGallery/standalone.props
This change retires the ProjectReunionPackageVersion and ProjectReunionWinUIPackageVersion variables that date back to the early days of the project.  The variable WindowsAppSdkPackageVersion is more correct and intuitive.
One less special case to remember
=> Replace ProjectReunion version variables with WindowsAppSdk ones

WinUIGallery/App.xaml.cs, WinUIGallery/Navigation/NavigationRootPage.xaml, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/PageHeader.xaml, WinUIGallery/PageHeader.xaml.cs
This PR introduces the following changes
- Adds an icon to the titlebar to resolve: #1177
- Sets ExtendsContentIntoTitleBar = true; in App.xaml.cs to resolve: #1178
- Removes a bunch of unused visual states (for e.g. Xbox and Mobile) and XAML.
- Replaces the C# logic for changing the titletext margins with simple visual states in XAML.
=> Titlebar improvements

WinUIGallery/Navigation/NavigationRootPage.xaml.cs
Fix double navigation
When a result item is selected, a method called `EnsureItemIsVisibleInNavigation` updates the selected item on the menu.
This triggers the `OnNavigationViewSelectionChanged` method, that navigates to the corresponding view.
But right after that, the navigation is called, causing it to navigate again.
https://github.com/microsoft/WinUI-Gallery/blob/2bf63f0697d3684ded6e66d4e48dfe68c3e8ba36/WinUIGallery/Navigation/NavigationRootPage.xaml.cs#L453-L454
This may be related to the issue https://github.com/microsoft/WinUI-Gallery/issues/972
After the change, the app navigates only once to the view.
=> Fix double navigation when selecting search result item.

WinUIGallery/ControlPages/GridViewPage.xaml
Changed ListView to GridView and changed the template name to ImageOverlayTemplate.
On the GridView control page in the second "GridView with Layout Customization" example, within the comments of the psuedo XAML code I changed the erroneous reference to "ListView" to the correct reference of "GridView" and corrected the template name to "ImageOverlayTemplate".
This resolves issue #1130 
The incorrect comment that existed previously would be confusing to a user attempting to follow the provided psuedo source code.
I ran the corrected version of WinUI Gallery on my local computer and the comment is now displaying correctly.  See screen shot below.
=> #1130 Corrected source code comments displayed to user

WinUIGallery/NuGet.Config, WinUIGallery/SettingsPage.xaml, WinUIGallery/SettingsPage.xaml.cs, WinUIGallery/WinUIGallery.DesktopWap.csproj, WinUIGallery/standalone.props, nuget.config
This PR introduces a new UX for the Settings page that is inline with Windows 11, inbox applications and the Windows Design Guidelines.
It uses the Windows Community Toolkit SettingsCard and SettingsExpander.. more information here: https://github.com/CommunityToolkit/Labs-Windows/discussions/129
=> New Settings UX

WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml, WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml.cs, WinUIGallery/WinUIGallery.DesktopWap.csproj
This PR removes the ToggleButtons with the Segmented control from the Windows Community Toolkit, as per design spec.
=> Using segmented control for colors page

WinUIGallery/SettingsPage.xaml
The Navigation Style was using an incorrect description:
=> [Settings] Incorrect description

WinUIGallery/ControlPages/DesignGuidance/AccessibilityScreenReaderPage.xaml, WinUIGallery/Controls/ControlExample.xaml, WinUIGallery/Controls/PageHeader.xaml
Today, the **Screen reader** guidance does not include `FullDescription` documentation, and it also implies that many properties must be set manually. This change fills those gaps and clarifies some aspects of designing for screen readers.
> This is intended to be the first of a few edits to the accessibility section.
There are new accessibility pages in the gallery, each with concrete examples. This change clarifies some examples and adds more:
* Accessible name
* Add a more robust description of accessible name
* Add examples of automatic accessible name
* Moved redundant controls to Raw view
* FullDescription, HelpText, and PosInSet
* Add overall description of these common properties
* Add example of FullDescription and HelpText
* Add example of automatic PosInSet/SizeOfSet
* Visual …
=> [Screen reader] Describe automatic properties and add FullDescription

WinUIGallery/ControlPages/ImplicitTransitionPage.xaml
By doing a port of changes in internal WinUI galllery repo to github  one, I accidentally removed a visual fix which was done by @gregwoo. Adding it back now.
Commit in ref: https://github.com/microsoft/WinUI-Gallery/commit/630214e39856b657e4567e1498ca9f231e216f2c
=> Re-doing visual bug fix which got removed by previous commit

WinUIGallery/ControlPages/TitleBarPage.xaml.cs, WinUIGallery/Controls/ControlExample.xaml.cs, WinUIGallery/Controls/SampleCodePresenter.xaml.cs
Both XamlSource and CodeSource variables use relative URIs, but are inferred to be absolute. This leads to false lookups under 
ms-resource://Files/<value> which doesn't exist.  The fix is to specify the relative paths as strings until we are ready to use them in an actual URI.
Also fixes for whitespace and unused namespaces.
=> Fix use of relative Uris

WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/DataModel/ControlInfoDataSource.cs, WinUIGallery/ItemPage.xaml.cs
add **Folder** property ControlInfoDataGroup
if present it will be appended to base URL when navigating to source code for all child items.
fixes #1232
Manual
=> fix incorrect links

WinUIGallery/Controls/PageHeader.xaml
The copy link button was missing an accessible name, resulting in it not being announced (correctly) by Narrator.
=> Adding accessible name to copy link button

WinUIGallery/ControlPages/DesignGuidance/AccessibilityKeyboardPage.xaml, WinUIGallery/ControlPages/DesignGuidance/AccessibilityKeyboardPage.xaml.cs, WinUIGallery/ControlPages/DesignGuidance/AccessibilityScreenReaderPage.xaml, WinUIGallery/DataModel/ControlInfoData.json
Today, our **Keyboard support** section does not include information about access keys or arrow keys, and doesn't have much documentation about default behavior or reference documents. This change adds guidance for access keys, arrow keys, and more, and documents the expected and default behavior for many of them.
Fixes #1229
Fixes #1225 
Fixes #1226
* Tab order
* Added example of default behavior.
* Clarified guidance & added documentation links.
* Updated manual tab order example to differ from default behavior.
* Arrow keys
* Added arrow keys section, with default example and custom example using `XYFocusKeyboardNavigation`.
* Documented common expectations for arrow keys, like Home/End, PgUp/PgDn, and PosInSet/SizeOfSet.
* Accelerators
* Demonstrate the default tooltip for keyboard …
=> [Accessibility][Keyboard support] Add access keys & arrow keys docs and add clarify guidance

WinUIGallery/Common/FileLoader.cs, WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/DataModel/ControlInfoDataSource.cs, WinUIGallery/DataModel/IconsDataSource.cs, WinUIGallery/Navigation/NavigationRootPage.xaml.cs
Using System.Text.Json.JsonSerializer instead of JsonObject for deserializing ControlInfoData.json file.
By using JsonSerializer, the codes become simpler and less, and we can use Async/Await
https://github.com/microsoft/WinUI-Gallery/discussions/1270
- Using JsonSerializer
- Remove unnecessary items from ControlInfoData.json
- Bring Back Icons to NavigationViewItem  (Why has no one noticed it?)
Tested On my Laptop
=> Using JsonSerializer instead of JsonObject

WinUIGallery/App.xaml, WinUIGallery/App.xaml.cs, WinUIGallery/NewControlsPage.xaml, WinUIGallery/NewControlsPage.xaml.cs, WinUIGallery/SettingsPage.xaml, WinUIGallery/SettingsPage.xaml.cs, WinUIGallery/WinUIGallery.DesktopWap.csproj
Uses auto-init bootstrapper version info contained in WindowsAppSDK-VersionInfo.cs to generate version strings for Home and Settings pages.  This also demonstrates how app developers can use version info for other purposes.
=> Display Windows App SDK and Runtime version info

WinUIGallery/Helper/WindowHelper.cs, WinUIGallery/ItemPage.xaml, WinUIGallery/Navigation/NavigationRootPage.xaml, WinUIGallery/SettingsPage.xaml.cs
The WinUI Gallery now has `Mica` as it's background, addressing: https://github.com/microsoft/WinUI-Gallery/issues/1066
- Added `Mica` to the MainWindow
- Removing unused code from `SettingsPage.xaml.cs`
Before vs. after
Theme switching
https://github.com/microsoft/WinUI-Gallery/assets/9866362/449e5271-ec74-4fd5-bbc1-954150f8b415
=> [UX] Adding Mica

WinUIGallery/ContentIncludes.props, WinUIGallery/ControlPages/SystemBackdropsPage.xaml, WinUIGallery/ControlPages/SystemBackdropsPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample1.txt, WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample2.txt, WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample3.txt, WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample4.txt, WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/SamplePages/SampleBuiltInSystemBackdropsWindow.xaml, WinUIGallery/SamplePages/SampleBuiltInSystemBackdropsWindow.xaml.cs, WinUIGallery/SamplePages/SampleSystemBackdropsWindow.xaml, WinUIGallery/SamplePages/SampleSystemBackdropsWindow.xaml.cs, WinUIGallery/WinUIGallery.DesktopWap.csproj
Updating the Mica sample now that it is available in WASDK 1.3, and way easier to implement!
_Note: This is a port from internal repo PR - 8915253_
Fixes #1286
=> Mica Sample Update

WinUIGallery/Helper/NavigationOrientationHelper.cs, WinUIGallery/Navigation/NavigationRootPage.xaml, WinUIGallery/Navigation/NavigationRootPage.xaml.cs
This PR addresses the following issues:
- Titlebar text color now changes when the window is not in focus as per best practices - addressing: #108
- Titlebar now acts correctly in Left and Top mode, addressing: #1203 and #1142
Before: 
After:
=> [UX] Titlebar improvements

WinUIGallery/ControlPages/DesignGuidance/AccessibilityColorContrastPage.xaml, WinUIGallery/Controls/InlineColorPicker.xaml
This PR increases the MinWidth of the color textbox so that when selected the user can read the entire HEX value without the clear button getting in the way. Addressing: https://github.com/microsoft/WinUI-Gallery/issues/1265
Before:
After:
=> [A11y] Increasing MinWidth of color textbox

WinUIGallery/ControlPages/InfoBadgePage.xaml
Fixes #770, Fixes #771 (I don't think adding interactivity is necessary here)
=> Fix a11y issue on InfoBadge sample

WinUIGallery/App.xaml, WinUIGallery/ControlPages/AppBarButtonPage.xaml.cs, WinUIGallery/ControlPages/BreadcrumbBarPage.xaml, WinUIGallery/ControlPages/BreadcrumbBarPage.xaml.cs, WinUIGallery/ControlPages/DesignGuidance/AccessibilityColorContrastPage.xaml, WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml, WinUIGallery/ControlPages/IconElementPage.xaml, WinUIGallery/ControlPages/SplitButtonPage.xaml, WinUIGallery/Controls/DesignGuidance/ColorPageExample.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/TextSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorTile.xaml, WinUIGallery/Controls/DesignGuidance/ColorTile.xaml.cs, WinUIGallery/Controls/InlineColorPicker.xaml, WinUIGallery/Controls/InlineColorPicker.xaml.cs, WinUIGallery/Controls/PageHeader.xaml.cs, WinUIGallery/Controls/TileGallery.xaml.cs, WinUIGallery/ItemPage.xaml.cs, WinUIGallery/WinUIGallery.csproj
This PR includes a handful of accessibility bug fixes. 
- [Bug 44665966](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/44665966): [WinUI Accessibility: Design guidance -> Accessibility -> Color contrast ]: No proper label name is defined to the split buttons present under Color Contrast Checker group.
- `InlineColorPicker` UserControl is updated to be compliant
- [Bug 44672713](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/44672713): [WinUI Accessibility: Design guidance -> Accessibility -> Color contrast ]: Text color, Background color and Contrast ratio text present under Color Contrast Checker group is not visible in high contrast Aquatic and Desert themes.
- Background is updated to the correct brush
- [Bug …
=> Miscellaneous Acessibility Fixes

WinUIGallery/ControlPages/BreadcrumbBarPage.xaml.cs, WinUIGallery/DataModel/ControlInfoDataSource.cs, WinUIGallery/WinUIGallery.csproj
- Add missing namespace in BreadCrumBar.xaml.cs
- Add `#Nullable enable` to disable build warning
- Move compile include line to more appropriate location.
=> Build Errors and Warning Fixes

WinUIGallery/ControlPages/MediaPlayerElementPage.xaml, WinUIGallery/ControlPages/MediaPlayerElementPage.xaml.cs
=> Pause media playback when navigating away from mediaplay page

UITests/Tests/TextBox.cs
Multiple PRs (e.g. #1304 and #1343) had the CI report failures because the TextBox test failed to type all characters. 
We avoid this issue by simply typing a lot less in those tests.
=> Update TextBox UI test to type less text to decrease flakyness

WinUIGallery/ControlPages/ListViewPage.xaml
=> Fix sample code missmatch on ListView page

WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml, WinUIGallery/Controls/HomePageHeaderImage.xaml, WinUIGallery/Controls/HomePageHeaderImage.xaml.cs, WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/ItemPage.xaml, WinUIGallery/SettingsPage.xaml, WinUIGallery/WinUIGallery.csproj, WinUIGallery/standalone.props, nuget.config
Upgrading to our new Toolkit 8.x packages.
This PR:
- Moves Toolkit packages to 8.0
- Removes the Labs preview feed, as packages are now available on the public nuget feed.
- Updating a bunch of Toolkit related namespaces
- XAML styling kicked in when editing a few .XAML packages
=> Upgrading to Toolkit 8.x

WinUIGallery/ControlPages/SystemBackdropsPage.xaml, WinUIGallery/ControlPages/SystemBackdropsPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample1.txt, WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample2.txt, WinUIGallery/SamplePages/SampleSystemBackdropsWindow.xaml.cs
Add new Desktop Acrylic Kind (Base and Thin) Introduced in WASDK 1.4
Tested On my Laptop
=> Add new Desktop Acrylic kind (Base and Thin)

WinUIGallery/Directory.Build.props, WinUIGallery/WinUIGallery.csproj, nuget.config
This PR resolves a few issues discovered in updating the WinUI submodule.
=> Fixes for WinUI submodule compatibility

WinUIGallery/Properties/PublishProfiles/win10-arm64-unpackaged.pubxml, WinUIGallery/Properties/PublishProfiles/win10-arm64.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x64-unpackaged.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x64.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x86-unpackaged.pubxml, WinUIGallery/Properties/PublishProfiles/win10-x86.pubxml
See:
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0
=> Set TrimMode explicitly back to partial for .NET 7 compat

WinUIGallery/ConnectedAnimationPages/CollectionPage.xaml, WinUIGallery/ConnectedAnimationPages/CollectionPage.xaml.cs, WinUIGallery/ControlPages/ClipboardPage.xaml.cs, WinUIGallery/ControlPages/DesignGuidance/AccessibilityKeyboardPage.xaml, WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml, WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml.cs, WinUIGallery/ControlPages/DesignGuidance/TypographyPage.xaml, WinUIGallery/ControlPages/FilePickerPage.xaml.cs, WinUIGallery/ControlPages/ItemsViewPage.xaml, WinUIGallery/ControlPages/ListViewPage.xaml, WinUIGallery/ControlPages/ListViewPage.xaml.cs, WinUIGallery/ControlPages/ProgressRingPage.xaml, WinUIGallery/Controls/DesignGuidance/ColorTile.xaml.cs, WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/Navigation/NavigationRootPage.xaml.cs
Miscellaneous p1 accessibility fixes:
- [Bug 44661786](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/44661786): [WinUI Accessibility: Design guidance -> Accessibility-> Keyboard support]: Screen reader is announcing incorrect information about the shortcuts.
- [Bug 46762667](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/46762667): [WinUI 3 Gallery: Item View]: Screen reader fails to announce the label for the radio buttons present in under 'Layout' group.
- [Bug 46763238](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/46763238): [WinUI 3 Gallery: Progress Ring]: Accessibility name and visual name is not same for working toggle button present under 'Toggle Work' group.
- [Bug …
=> P1 Accessibility Fixes

WinUIGallery/App.xaml.cs, WinUIGallery/ControlPages/CreateMultipleWindowsPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/Window/CreateWindowSample1.txt, WinUIGallery/HomePage.xaml, WinUIGallery/HomePage.xaml.cs, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/Strings/en-US/Resources.resw
Renames the NewControls page to HomePage since the menu item is called "Home" and showing new control samples is no longer its only purpose.
Part of #1279
=> Rename NewControls page to Homepage

WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml, WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml.cs
The ItemsRepeater for IconsPage has too many accessibility issues including lack of keyboard navigation and narrator announcement. Refactored to ItemsView that has all of it built in. 
Also added Narrator announcement when filtered items have changed.
[Bug 44661633](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/44661633): [WinUI Accessibility: Design guidance -> Icons]: Unable to navigate and access the Icons present under “Fluent Icons Library” using keyboard.
[Bug 44661471](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/44661471): [WinUI Accessibility: Design guidance -> Icons]: Screen reader fails to announce regarding the available suggestions.
Manual verification
=> Refactor IconsPage ItemsRepeater to ItemsView

WinUIGallery/ControlPages/GridViewPage.xaml
Due to a missing BasedOn, the selection indicator and other interface characteristics where missing on the custom layout sample.
Fixes #1072
=> Fix Selection Indicator for GridView sample

WinUIGallery/Controls/SampleCodePresenter.xaml.cs
The sample presenter did not properly determine if it was empty resulting in it not hiding despite it being empty.
Fixes #1373
=> Fix sample presenter not properly determing if its empty

WinUIGallery/ControlPages/FlyoutPage.xaml, WinUIGallery/ControlPages/FlyoutPage.xaml.cs
As title.
Found something not working about changing the flyout mode in the current version of winui, so I added this example and confirmed it.
The [issue here](https://github.com/microsoft/microsoft-ui-xaml/issues/7987)
Manually
=> Add a custom showmode example in flyout page

WinUIGallery/ControlPages/XamlCompInteropPage.xaml.cs
Fixes issues with the damping sample since we weren't using 0.2, 0.4 etc but sometimes 2,4,... as damping ratio depending on the users locale
Fixes #1049
=> Fix damping sample misbehaving when using wrong locale

WinUIGallery/Helper/NavigationHelper.cs, WinUIGallery/Navigation/NavigationRootPage.xaml.cs
Adding back the usage of the NavigationHelper to allow navigating between pages. Note that certain APIs are missing in WinUI 3 compared to UWP so we are diverging from the WinUI 2 version here.
Fixes #1205
=> Readd navigation stack capabilities

WinUIGallery/ControlPages/ListBoxPage.xaml
This change updates the Width set on ListBox to be MinWidth instead.
This fixes an accessibility issue in WinUI3 Gallery, where ListBox would truncate longer text when text scaling is sized up. 
Ad-hoc testing
=> Fix Listbox text truncation when text is scaled up

azure-pipelines.yml
Cleans up pipeline and adds displaynames for steps
=> Cleanup azure pipelines steps

WinUIGallery/ControlPages/DropDownButtonPage.xaml
Once [PR 9838266: Fix text truncation on DropDownButton MenuFlyout](https://microsoft.visualstudio.com/WinUI/_git/microsoft-ui-xaml-lift/pullrequest/9838266) is completed, DropDownButton's MenuFlyout will no longer truncate longer text when text is scaled up. As a result, at the WinUI3 Gallery app-level, we need to set MenuFlyout's Placement to BottomEdgeAlignedLeft, so that longer text will not end result in MenuFlyout covering the NavigationView.
This helps resolve an accessibility issue, in tandem with controls-side changes in the above mentioned PR.
Ad-hoc testing
=> Change DropDownButton's MenuFlyout Placement to be left-aligned

WinUIGallery/App.xaml.cs
Note: Microsoft.WindowsAppRuntime.Insights.Resource.dll is the only module that carries complete version info.
=> change Windows App Runtime version to actually reflect runtime, not SDK

WinUIGallery/ControlPages/ListBoxPage.xaml
The ListBox example is missing `/` in the closing tags of the options
Examples shouldn't have invalid syntax
N/A
=> Fixing `ListBox` XAML code example syntax

WinUIGallery/ControlPagesSampleCode/System/FilePickerSample1_cs.txt
Corrected a little mistake in the sample text document. I added a curly brace at the end of the file.
I found the issue while using the app, as I tried to copy the code part, and then I came across the mistake.
Its just a txtFile, no tests needed.
=> Added Missing Curly Brace in Sample Text Document

WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml, WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml.cs, WinUIGallery/Controls/DesignGuidance/ColorSections/HighContrastSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/HighContrastSection.xaml.cs, WinUIGallery/WinUIGallery.csproj
This PR adds a `High Contrast` page to the colors overview, and shows the 8 high contrast brushes that come with WinUI.
This closes: #1217
New high contrast page:
Screenshot from WinUI Visual Library Figma (source):
=> [Colors] Adding highcontrast brushes

WinUIGallery/ControlPages/AppBarButtonPage.xaml, WinUIGallery/ControlPages/AppBarToggleButtonPage.xaml, WinUIGallery/ControlPages/InfoBadgePage.xaml
Escape glyph hex in xaml sample
->
=> Fix: Escape glyph hex in xaml

WinUIGallery/ControlPages/SemanticZoomPage.xaml
_See title_
No big deal, just a nit.
- Bug fix (non-breaking change which fixes an issue)
=> nit: merge two StackPanels

WinUIGallery/ControlPages/ListViewPage.xaml.cs
This issue was brought up here:
[JAWS cannot read non-simple ListViewItems · Issue #8109 · microsoft/microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml/issues/8109)
We update the ToString of the data item in the ListView to include both the Name and the Company which gives a better experience for screen readers.
=> Improve accessibility of ListView page - list view items UIA description includes more information.

WinUIGallery/ControlPages/EasingFunctionPage.xaml
Add exponent settings to easing function page
Sometimes I just need to have a quick tryout to different values using this
Manual.
=> Add exponent settings to easing function page

WinUIGallery/ControlPagesSampleCode/Motion/AnimationInterop/AnimationInteropSample4_cs.txt, WinUIGallery/ControlPagesSampleCode/Motion/AnimationInterop/AnimationInteropSample5_cs.txt
Remove api check in code sample of winui3 animation interop page
Because it's unnecessary. WinUI3 has decoupled compositor
Manual
=> Remove useless api check in the animation interop page code sample

UITests/AxeHelper.cs, UITests/SampleTestTemplate.cs, UITests/SessionManager.cs, UITests/TestBase.cs, UITests/Tests/Button.cs, UITests/Tests/CheckBox.cs, UITests/Tests/ComboBox.cs, UITests/Tests/DatePicker.cs, UITests/Tests/MediaPlayerElement.cs, UITests/Tests/PersonPicture.cs, UITests/Tests/ProgressBar.cs, UITests/Tests/RadioButton.cs, UITests/Tests/Slider.cs, UITests/Tests/TextBlock.cs, UITests/Tests/TextBox.cs, UITests/Tests/ToggleButton.cs, UITests/Tests/ToggleSwitch.cs, WinUIGallery/Properties/AssemblyInfo.cs
Updates copyright year in tests and changed copyright string to match other Microsoft products (example: https://github.com/microsoft/PowerToys/pull/30689/files)
New year and similarity with other Microsoft Products
=> Update copyright year and copyright string

.github/ISSUE_TEMPLATE/bug_report.yaml
Fixed the YAML syntax on "labels".
The "Bug report" issue template is not working due to this error.
Checked that the syntax error is fixed on a local branch.
=> Fix YAML syntax error on bug_report.yaml

WinUIGallery/DataModel/ControlInfoData.json
Updated AnnotatedScrollBar icon from Placeholder.png to ScrollViewer.png.
ScrollView and ScrollViewer are using ScrollViewer.png .
Run the app and checked that the icon is updated to ScrollViewer.png
=> Update AnnotatedScrollBar icon

UITests/Tests/SearchResults.cs, WinUIGallery/DataModel/ControlInfoDataSource.cs
Set the placeholder image "Placeholder.png" in case that ControlInfoDataPath item's ImagePath is null.
Fixes #1438.
Tested on the updated app.
=> Fix app crash trying to show the search results page

Directory.Build.props, UITests/README.md, UITests/UITests.csproj, WinUIGallery/Directory.Build.props, WinUIGalleryUnitTests/WinUIGalleryUnitTests.csproj, standalone.props
WinUIGallery's dependencies now require latest SDKs, so should specify these regardless of how the project is built (standalone vs submodule).
The unit test project was not setting standalone properties properly - factored out common directory.build.props.
Added a workaround for conflicting build and publish deps.json files until WinAppSDK provides the fix.
=> Update to support submodule builds

WinUIGallery/ControlPagesSampleCode/System/FilePickerSample1_cs.txt
There was a mismatch in the name for TextBlock control in the first FilePicker sample. Changed name from `OutputTextBlock` to `PickAFileOutputTextBlock` in the sample source text file.
N/A, typo fix.
=> [FIX] Fix typo in file picker sample source

WinUIGallery/DataModel/ControlInfoData.json
Change Pivot control's description back to plain text since html tags are not supported here.
Closes #1504 
Run the app and confirmed that the `Pivot` description doesn't have html tags.
=> Fix Pivot control's description

WinUIGallery/Controls/ControlExample.xaml, WinUIGallery/Controls/SampleCodePresenter.xaml
Remove padding of UserControl and Grid, and set (bottom)margin on ContentPresenter.
fixes #1489, ~1501~
P.S. It's **Styler** that moved the **VisualStateManager** bits around
=> adjust code padding

WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/DataModel/ControlInfoDataSource.cs, WinUIGallery/ItemPage.xaml.cs
Replace hardcoded version numbers embedded in source URIs with associated WASDK version numbers.
=> Set URI source version numbers dynamically to simplify maintenance

WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml, WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml.cs, WinUIGallery/Controls/DesignGuidance/ColorPageExample.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/HighContrastSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/TextSection.xaml
Replacing the ComboBox with the SelectorBar so it's easier to see all the different categories of colors and immediately jump to those.
=> [Colors] Replace ComboBox with SelectorBar

WinUIGallery/App.xaml.cs, WinUIGallery/Common/Win32.cs, WinUIGallery/Helper/NavigationHelper.cs
Adding support for X1/X2 Mouse Button and WinKey + Backspace to navigate.
With this PR, we are also switching to KeyboardProcHook since the old way didn't allow us to handle WinKey+Backspace to navigate back.
Fixes #1465
=> Implement better keyboard handling, add missing navigation shortcuts/keys

WinUIGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
This PR removes the code that blocked dragging the last tab. I think this also addresses the other open issue since we might not have properly updated the tab-allowance state.
Closes #399
=> Allow dragging last tab out of window

WinUIGallery/DataModel/ControlInfoData.json
Quick update to the description (copy from MS Learn)
Text is outdated / does not apply.
fixes #1518
=> Update CommandBar description

WinUIGallery/Controls/DesignGuidance/ColorSections/SignalSection.xaml
- Updated text to match content: "System / Critical Background". Fixing a typo.
- Also set **IsClosable="False**" on the InfoBar, because when it's closed, user needs to nav to the page again to see it.
Incorrect text.
Illogical use case for InfoBar.
=> Update SignalSection: "System / Critical" and IsClosable="False"

WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/ItemPage.xaml
This PR fixes an incorrect padding being used when the window has a small window width. The `PageHeader` control would not align correctly with the page content.
Addressing: https://github.com/microsoft/WinUI-Gallery/issues/1502
Before:
After:
=> Fix pageheader spacing at smaller window widths

WinUIGallery/ControlPages/DesignGuidance/ColorPage.xaml, WinUIGallery/ControlPages/DesignGuidance/GeometryPage.xaml, WinUIGallery/ControlPages/DesignGuidance/SpacingPage.xaml, WinUIGallery/ControlPages/DesignGuidance/TypographyPage.xaml, WinUIGallery/Controls/DesignGuidance/TypographyControl.xaml
few suggestions, as also commented in  #1531
feel free to adapt where needed
=> Design suggestions

WinUIGallery/DataModel/ControlInfoData.json
I ate my [own words](https://github.com/microsoft/WinUI-Gallery/pull/1508#issuecomment-2013992248) - Pivot is **NOT** deprecated. It is instead "not recommended".
Updated pivot description to what is in the [dev docs](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.pivot?view=windows-app-sdk-1.5).
=> Update Pivot Recommendation

WinUIGallery/ControlPages/EasingFunctionPage.xaml, WinUIGallery/ControlPages/TitleBarPage.xaml.cs, WinUIGallery/Navigation/NavigationRootPage.xaml
- `AppTitleBarTextBox` 's `Width` is not set, so `Width +=1 ` does nothing
- The `SizeChanged` event handler is called **once**, because of `Visibility` changed, and it was put in a `StackPanel` that's vertically constrained, so the size change will occur once, not because `Width += 1`. Consecutive adding it to the title bar no longer triggers the event handler, therefore the issue
- And `Width += 1` is a dirty hack anyway, does not need that.
Close #1470
Manual.
=> Fix: Interactive element is no longer interactive after adding it a second time

WinUIGallery/DataModel/IconsData.json
Corrects the Japanese icon name used in the **Icons** page.
The correct word is "ROMAJI" and not "ROMANJI".
Confirmed by checking the **Icons** page.
=> Correct Japanese icon name

WinUIGallery/ControlPages/TitleBarPage.xaml
Add link to TitleBar Experimental samples:
=> Link to TitleBar Experimental Samples

WinUIGallery/ControlPages/DesignGuidance/GeometryPage.xaml, WinUIGallery/ControlPages/DesignGuidance/SpacingPage.xaml
Few small things
...that weren't perfect
I would also suggest this icon (yay or nay?)
(before)
=> Details on new pages

WinUIGallery/Controls/DesignGuidance/ColorSections/TextSection.xaml
Update text color for the tertiary and disabled brush colours to satisfy colour contrast for accessibility:
Fixes internal bug: 
[Bug 51099086](https://dev.azure.com/microsoft/OS/_workitems/edit/51099086): [WinUI 3 Gallery: Design Guidance: Color]: Color contrast ratio for "Text / Disabled" text is 2.77:1 which is less than 4.5:1.
**Before:**
**After:**
=> TextSection Color Design Guidance Update Color Contrast 

WinUIGallery/Package.Dev.appxmanifest, WinUIGallery/Package.appxmanifest, WinUIGallery/Properties/AssemblyInfo.cs, standalone.props
- Update WASDK dependency to latest stable: [1.5.4 ](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.5.240607001)
- Update WinUI-Gallery version number to 2.4.2.1
=> Update to WASDK 1.5.4

WinUIGallery/ControlPages/DesignGuidance/IconographyPage.xaml.cs, WinUIGallery/DataModel/IconsData.json, WinUIGallery/DataModel/IconsDataSource.cs
Closes #1544.
This PR will enable searching icons based on tags on the Iconography page. Icon tags are assigned on the IconsData.json file.
The current icon searching is based only on the icon name or its code. Some icon's names are not very intuitive, or some icons can represent several things. So, to get an icon code and if you don't know the icon name, you need to search it manually by scrolling through more than 1400 icons.
Tested on the VS.
=> Searching icons by tags

WinUIGallery/Helper/Win32WindowHelper.cs
Modify the code to avoid potential problems(in 'WinUIGallery/Helper/Win32WindowHelper.cs')
max may have been incorrectly written as min in the code
By analyzing the code, it can be inferred that there might be a problem here.
Manual test
=> Fix: A potential bug in Win32WindowHelper.cs

WinUIGallery/DataModel/ControlInfoData.json
Fix RadioButtons image abnormal.
make RadioButtons image see normal.
1.click Layout at NavigationView;
2.you can see abnormal.
abnorml:
after fix this it show normal.
normal:
=> Fix RadioButtons image abnormal.

WinUIGallery/ControlPages/ComboBoxPage.xaml, WinUIGallery/ControlPages/RichEditBoxPage.xaml, WinUIGallery/ControlPages/StandardUICommandPage.xaml, WinUIGallery/ControlPages/ToolTipPage.xaml, WinUIGallery/ControlPages/XamlCompInteropPage.xaml, WinUIGallery/ControlPages/XamlUICommandPage.xaml, WinUIGallery/Controls/ControlExample.xaml, WinUIGallery/Controls/ControlExample.xaml.cs, WinUIGallery/Helper/UIHelper.cs, WinUIGallery/ItemPage.xaml.cs, WinUIGallery/SettingsPage.xaml, WinUIGallery/SettingsPage.xaml.cs
This PR removes screenshot mode and some MinimumContract checks that was UWP specific.
Fixes #1569
=> Remove unused code

WinUIGallery/ControlPages/SoundPage.xaml, WinUIGallery/ControlPages/SoundPage.xaml.cs
See screenshot.
Previously the sound demo requires toggling the ComboBox, but the ComboBox itself will have an element sound too, causing some confusion. Also the ComboBox item ordering is incorrect (MovePrevious -> MoveNext is the correct order)
Manual
=> Feat: Better xaml sound demo

WinUIGallery/ControlPages/TextBlockPage.xaml
As title suggest.
Many people are not aware of `TextBlock` is selectable and use `TextBox` instead which may have higher overhead. So I made this sample.
Mnaual
=> New sample: Selectable TextBlock

WinUIGallery/ControlPages/AutoSuggestBoxPage.xaml.cs
The individual control pages' IconGlyph are all `null`. Causing the crash in the AutoSuggestBox page.
Closes #1581
Manual.
=> Fix: AutoSuggestBox Page crash

WinUIGallery/WinUIGallery.csproj
Added a icon to the apps exe file.
Set the exe icon in the project properties to "Assets\Tiles\GalleryIcon.ico"
Don't know why the exe doesn't have an icon.
Fixed this issue: https://github.com/microsoft/WinUI-Gallery/issues/1600
No testing needed.
=> Add a icon to the exe file

WinUIGallery/Navigation/NavigationRootPage.xaml.cs
Changed the height of the Title Bar caption buttons (minimize, maximize, close) from 32px to 48px so it matches the height of the AppTitleBar UIElement.
Set the PreferredHeightOption of the Title Bar to Tall.
The current caption buttons look weird. The fix is also just one line.
No testing needed.
=> Title Bar height fix

WinUIGallery/ControlPages/ContentDialogPage.xaml.cs, WinUIGallery/Shaders/TwirlDismiss.cs
When rotating the contentdialog on dismiss, the corners would clip outside the bounds. This modifies the shader to morph the rectangle into a circle over the first quarter-turn, preventing the clip from happening.
=> Make twirl dismiss not clip when rotating

WinUIGallery/ContentIncludes.props, WinUIGallery/ControlPages/NumberBoxPage.xaml, WinUIGallery/ControlPages/NumberBoxPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/NumberBox/NumberBoxSample2_xaml.txt
This update ensures that the example code reflects user selections between `Inline` and `Compact` spin button placements, improving the accuracy and relevance of the displayed example, main changes are:
- **Updated** XAML to dynamically reflect spin button placement changes in the displayed code.
- Replaced static XAML with dynamic code binding that updates based on user selection.
- **Modified** `RadioButtons` control to use `SelectionChanged` event handler for updating the `SpinButtonPlacementMode` of the `NumberBox`.
- **Added** XAML substitution to ensure the displayed source code shows the correct `SpinButtonPlacementMode`.
- **Removed** obsolete XAML source file `NumberBoxSample2_xaml.txt`.
The previous implementation did not dynamically update the example source code based on user …
=> feat: Update NumberBox example to reflect spin button placement in displayed XAML code

WinUIGallery/ControlPages/ScrollViewPage.xaml, WinUIGallery/ControlPages/ScrollViewPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/ScrollView/ScrollViewSample3_AccordionAnimation_cs.txt, WinUIGallery/ControlPagesSampleCode/ScrollView/ScrollViewSample3_DefaultAnimation_cs.txt, WinUIGallery/ControlPagesSampleCode/ScrollView/ScrollViewSample3_TeleportationAnimation_cs.txt, WinUIGallery/Controls/SampleCodePresenter.xaml.cs, WinUIGallery/WinUIGallery.csproj
Updated ScrollView Animation sample to display C# code, include default, accordion, and teleportation animations, and fixed code visibility handling to prevent overlap. With dynamically updated animation duration in the code displayed, main changes are:
- **Added Sample Code Files**:
- Included three new sample code files for different scroll animations: - `ScrollViewSample3_DefaultAnimation_cs.txt` - `ScrollViewSample3_AccordionAnimation_cs.txt` - `ScrollViewSample3_TeleportationAnimation_cs.txt`
- **Updated Sample Code for Scroll Animations**:
- Provided sample code for three types of animations (Default, Accordion, Teleportation) to be used in the `ScrollView_ScrollAnimationStarting` method.
- **Updated Sample Code for Animation Duration Handling**:
- Implemented dynamic updating to …
=> fix: Update Scroll View Animation Example and Sample Code Presenter

WinUIGallery/ControlPages/SplitViewPage.xaml
A simple update to resolve discrepancies between the rendered content and the displayed source code, the only change is:
- Remove the code that does not match from the displayed source code (SplitViewPage.xaml).
- The similarity between SplitView and NavigationView might be confusing for learners, so it would be best to remove it.
- fixes this issue: https://github.com/microsoft/WinUI-Gallery/issues/1587
**Manually Tested**
=> SplitView Sample -> `fix` the mismatch between rendered content and source code

WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/DataModel/ControlInfoDataSchema.json
I added a schema file for the `ControlInfoData.json` to make adding new control / control group to it simpler. Now you get nice intellisense for all properties and error message for missing required ones. The schema should be automatically picked up by any reasonable editors.
I just happens to know this.
The current file reports no mismatch for this schema.
=> Add schema for ControlInfoData.json

WinUIGallery/ControlPages/DesignGuidance/SpacingPage.xaml
Fixing text on spacing page being hard to read when using the theme switch button. This was caused because we didn't include SampleThemeListener and the default behavior of ItemsPages is to switch the theme of the entire page if none are used in a sample page.
Fixes #1637
=> Fix theming in spacing page

WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/Shaders/CaptureHelper.cs, WinUIGallery/Shaders/IdentityShader.cs, WinUIGallery/Shaders/PixelShaderRenderer.cs, WinUIGallery/Shaders/RippleFade.cs, WinUIGallery/Shaders/ShaderPanel.xaml.cs, WinUIGallery/Shaders/ShaderSourceHelper.cs, WinUIGallery/Shaders/Wipe.cs
- Added an `IdentityShader` for debugging purposes
- Fixed pixel sampling positions to be pixel centered
- Correctly get back into pixel space in the ShaderPanel
- Transform our clip into pixel space too
- 100% DPI now looks perfectly crisp. Other DPIs still have issues.
=> Fix more DPI Issues for Demo

WinUIGallery/Navigation/NavigationRootPage.xaml.cs
Switching from the ripple effect to the wipe effect would cause the wipe effect to not appear, because part of the ripple effect is an opacity fade. This change fixes that to reset the opacity every time an effect is triggered.
=> Fix switching effects bug

WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/DataModel/ControlInfoDataSource.cs, WinUIGallery/ItemPage.xaml
Shows the base classes of each control/element.
This will help devs understand the inheritance structure of WinUI controls/elements.
Tested on VS.
=> Show item base classes

WinUIGallery/Navigation/NavigationRootPage.xaml.cs
Disable check to skip animation if an animation is already in progress.
We can re-enable this if we want it, but for now we'll restart the animation if a click happens again too fast.
=> [SceneGraph LKG] Disable check to skip animation if an animation is already in progress

WinUIGallery/ControlPages/ContentDialogPage.xaml.cs, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/Shaders/CaptureHelper.cs, WinUIGallery/Shaders/ShaderPanel.xaml.cs
This includes:
- Makes what happens if multiple pages are quickly clicked be more reasonable
- The average case should not hit this
- If clicking very quickly between two pages, we still play an animation but it targets the last clicked page
- If clicking before the previous animation is *quite* finished it will still queue up another animation now
- Fixes some crashes and other issues if clicking rapidly (like getting stuck scaled up)
- Deletes a lot of dead code
- Cleans up some logic and naming in the DialogContentPage so that it's nicer to show off
=> [SceneGraph LKG] Fix rapid clicking behavior + code cleanup

WinUIGallery/ControlPages/DesignGuidance/ColorPage.xaml
Added sample code for the theme resource brush use.
Ran the app and confirme the change.
Before:
After:
=> Improve Color page sample code

WinUIGallery/ControlPages/TitleBarPage.xaml, WinUIGallery/ControlPagesSampleCode/Window/TitleBar/TitleBarSample1.txt
This pull request Updates the TitleBar customization example by separating the XAML and C# code into distinct Code Presenters, main changes are:
- Adjusted the control example to include separate XAML code in `TitleBarPage.xaml`.
- Updated C# code in `TitleBarSample1.txt` to align with the new implementation.
This simple change enhances readability and avoids confusion.
**Manually tested**
Before changes:
After Changes:
=> Separate XAML and C# code in TitleBar customization example

WinUIGallery/ControlPages/ScrollViewPage.xaml, WinUIGallery/ControlPages/ScrollViewPage.xaml.cs, WinUIGallery/Controls/ControlExample.xaml, WinUIGallery/Controls/ControlExample.xaml.cs, WinUIGallery/Controls/SampleCodePresenter.xaml.cs
This PR reverts changes introduced in #1616 to the `ReevaluateVisibility` method in the `SampleCodePresenter` class. The modifications in #1616 caused unintended side effects, including the issue observed on the icons page. Reverting these changes resolves the problem and restores expected behavior.  
Additionally, this PR includes:  
- **Fix for overlapping issue with `SampleCodePresenter`:** Updates `ControlExample` to use `ContentPresenter` for visibility management, ensuring no overlapping when C# code changed.  
- **Ensure correct C# code sample updates when animation duration changes.**
Fixing the issue on the icons page caused by unintended side effects of changes in #1616, ensuring proper visibility management for code presenters without affecting other functionality. Additional …
=> Resolve `Iconography Page` issue, improve `Control Example` behavior and `ScrollViewPage` Example

WinUIGallery/ControlPages/DesignGuidance/ColorPage.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/BackgroundSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/FillSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/HighContrastSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/SignalSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/StrokeSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/TextSection.xaml
The changes in this PR prevent the `SampleThemeListener` from applying theme changes to all child elements, including some textboxes, which do not need to be affected by the theme toggle. These changes address the issue of inconsistent text highlighting in the "High Contrast" section of the `ColorPage` by improving theme handling. The main changes are:
- Removed `<SampleThemeListener>` from `ColorPage`.
- Added `<SampleThemeListener>` to other "Color Sections" pages as needed for better modularity.
Fixes #1671 
**Manually Tested** by toggling the theme in all sections of the `ColorPage` and observing the behavior.
=> Fix: `Color > HighContrast` theme toggle highlight

WinUIGallery/ItemPage.xaml.cs
A few weeks ago the WinUI source code moved to the `main` branch as it should be. Therefore, we no longer need to link to a specific branch/version number.
As a result, the source code links are working again!
Closes: #1681
=> Fix broken WinUI repo link

WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/Controls/PageHeader.xaml.cs, WinUIGallery/ItemPage.xaml
This PR moves the `Namespace` and `Inheritance` information in a flyout.
Closes #1678
=> [UX] Pageheader improvements

WinUIGallery/ControlPages/FilePickerPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample1_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample2_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample3_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample4_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample5_cs.txt
This PR will prevent double-clicking the button, preventing two FilePicker dialogs to appear at the same time.
Currently, if you click the buttons on FilePicker page fast enough, two FilePicker dialogs will show up. Code examples are also added to show a correct implementation.
Manual.
=> Fix: Prevent FilePicker button double-click

.github/ISSUE_TEMPLATE/bug_report.yaml
Fixed 24H2 build number in the issue template. The correct build is `26100` not `26052`.
=> Fixed 24H2 build number

.github/ISSUE_TEMPLATE/bug_report.yaml
Reverts microsoft/WinUI-Gallery#1703
While technically, 26052 was the first build of 24H2, 26100 are the GA releases and I think it makes more sense to stick with that version.
=> Revert "Fixed 24H2 build number"

.github/ISSUE_TEMPLATE/bug_report.yaml
Reverts microsoft/WinUI-Gallery#1715 since I failed to properly read the diff
=> Revert "Revert "Fixed 24H2 build number""

WinUIGallery/ControlPages/TeachingTipPage.xaml, WinUIGallery/ControlPages/TeachingTipPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/TeachingTip/TeachingTipSample1_xaml.txt, WinUIGallery/ControlPagesSampleCode/TeachingTip/TeachingTipSample2_xaml.txt, WinUIGallery/ControlPagesSampleCode/TeachingTip/TeachingTipSample3_xaml.txt
This PR updates the sample code on the `TeachingTip` page to match the actual code.
The current sample code doesn't match the actual code and doesn't even compile.
Ran the app and confirmed its contents.
=> Update the sample code to match the actual code

WinUIGallery/DataModel/ControlInfoData.json
Fixed the "WinUI Theme Resources (Github)" being broken.
Changed the link in "ControlInfoData.json" from "https://github.com/microsoft/microsoft-ui-xaml/blob/winui3/release/X.Y-stable/controls/dev/CommonStyles/Common_themeresources_any.xaml" to "https://github.com/microsoft/microsoft-ui-xaml/blob/winui3/release/X.Y-stable/src/controls/dev/CommonStyles/Common_themeresources_any.xaml"
Fixes https://github.com/microsoft/WinUI-Gallery/issues/1712
Manual
=> Fix the theme resource link

WinUIGallery/ControlPages/ListViewPage.xaml, WinUIGallery/ControlPages/ListViewPage.xaml.cs
Fixed spelling error in the ListView context menus example.
This change improves the readability of the example and code but does not impact functionality.
No testing required.
=> fix typo in ListView context menus example

WinUIGallery/App.xaml.cs
Cleaned up the app.xaml.cs file.
1.Removed UWP code from the file.
2.Added comments to the file.
3.Made the code cleaner.
4.Removed unused code.
UWP code should not be in a WinUI app.
No testing needed.
=> Clean up App.xaml.cs

WinUIGallery/App.xaml, WinUIGallery/ControlPages/DesignGuidance/IconographyPage.xaml, WinUIGallery/ControlPages/DesignGuidance/IconographyPage.xaml.cs, WinUIGallery/Controls/DesignGuidance/ColorPageExample.xaml, WinUIGallery/Controls/DesignGuidance/ColorTile.xaml, WinUIGallery/WinUIGallery.csproj
This PR introduces the following changes:
- Tweaks the UX of the Icon panel for better readability.
- Using an `ItemsView` without buttons, for better accessibility. Using a `WrapLayout` (from the WCT) so labels are not cut off.
- Selecting the first item upon loading, or after searching.
- Collapse the sidepanel until the grid icons is loaded: current behavior shows empty content on the right for 2 seconds which does not look great.
- Spacing tweaks for the color sections so they are clustered together a bit better
- Using a 0.8 opacity for the subtitle to be a bit less prominent
=> Minor UX tweaks for icons + color sections

WinUIGallery/ControlPages/RichEditBoxPage.xaml
[WinUI3 Gallery] [RichEditBox]: On applying Text Scaling to 200%, 'Enter search text' placeholder text is getting trimmed.
Removed the `Width` property from the `TextBox` element in the `RichEditBoxPage.xaml` file to prevent the placeholder text from getting trimmed when applying Text Scaling to 200
This is an Accessibility issue. User with low vision who rely on text scaling will be impacted and will face difficulties if the placeholder gets trimmed on application of Text Scaling to 200.
Made the changes in the code and tested the scenario by applying Text Scaling to 200% and verified that the placeholder text is not getting trimmed.
For scaling 225:
For scaling 100:
=> [WinUI3 Gallery] [RichEditBox]: On applying Text Scaling to 200%, 'Enter search text' placeholder text is getting trimmed

WinUIGallery/Pages/AllControlsPage.xaml.cs
To test:
- Click on All Samples
- All Samples item should now be selected, vs "Accessibility"
Closes: https://github.com/microsoft/WinUI-Gallery/issues/1742
=> Fix All Samples selection

WinUIGallery/Samples/ControlPages/DesignGuidance/IconographyPage.xaml
- Fix scrolling issue by removing a `ScrollViewer` that wasn't needed at all.
- Fix the background issues for the icon snippets:
Before:
After:
=> Fix icon tool issues

WinUIGallery/Samples/ControlPages/DesignGuidance/IconographyPage.xaml
=> Icon tool design fix

WinUIGallery/Samples/ControlPages/XamlFundamentals/ScratchPadPage.xaml, WinUIGallery/Samples/ControlPages/XamlFundamentals/ScratchPadPage.xaml.cs
I noticed that the interactive area of the page did not receive any mouse input. Keyboard did work. I saw that conversion for `RowDefinitions="*, Auto"` was applied to the incorrect (child) Grid, causing the TextBlock to be in the same Grid cell as the RichInput.
Fix blocked input
=> ScratchPadPage.xaml was broken, Grid was blocked

WinUIGallery/Samples/ControlPages/TreeViewPage.xaml
This PR fixes an issue in the `TreeViewPage` where the folder icon image was not displaying correctly due to project restructuring. The image source was using a relative path, which became invalid after the changes.
Updated the image path to ensure the icon displays correctly.
Before:
After:
=> Fix `TreeView` Example Icon Path Issue After Restructuring

WinUIGallery/Samples/ControlPages/TabViewPage.xaml, WinUIGallery/Samples/ControlPages/TabViewPage.xaml.cs
Closes #815.
This PR fixes an auto-scrolling issue on the TabView page.
What I found out is that the `TabView` control is firering `BringIntoViewRequested` events when `TabWidthMode` is set to `SizeToContent` or `Compact`. Handling the `BringIntoViewRequested` event stopped the auto-scrolling.
Ran the app and verified the changes.
=> Fix auto-scrolling issue on the TabView page

WinUIGallery/Samples/ControlPages/Fundamentals/TemplatesPage.xaml.cs
Fixed an app crash on the Templates page when changing the radio button in the third example. The issue was caused by the structural change in the app, which made the old file path invalid. Updated **ReadSampleCodeFileContent** to use the correct path (**Samples\\SampleCode\\Templates**) to resolve the issue.
=> Fix crash on Templates page due to incorrect file path

WinUIGallery/Samples/ControlPages/Design/GeometryPage.xaml, WinUIGallery/Samples/ControlPages/Design/SpacingPage.xaml, WinUIGallery/Samples/ControlPages/Design/TypographyPage.xaml, WinUIGallery/Samples/ControlPages/PullToRefreshPage.xaml
Remove `ScrollViewer` from `PullToRefresh` page and hide vertical scrollbar in `Geometry`, `Spacing`, and `Typography` pages.
The `ScrollBar` was visible even when there was no need to scroll, making the screen look cluttered. These changes ensure a cleaner and more polished UI.
**Manually** tested
=> Improve Scroll Behavior on Various Pages

WinUIGallery/Samples/Data/ControlInfoData.json
- A few items in the NavView were either not alphabetically sorted, or just had a weird ordering in general.
- Moved ItemsRepeater under Collections. This control is more used in context of binding a collection, like ItemsView/ListView etc. vs. in context of a layout panel like a Grid or StackPanel
=> Minor menu reordering

WinUIGallery/Controls/ControlExample.xaml
This PR eliminates the unnecessary top and bottom space occupied by the sample code in the source code expander. The only change is updating the `Padding` of the `Expander` element to improve layout and content spacing.
For a better and cleaner UX.
**Before**
**After**
=> Update the spacing in the sample code display of the `ControlExample` control

WinUIGallery/Samples/SampleCode/AppWindow/AppWindowSample4_cs.txt, WinUIGallery/Samples/SamplePages/ModalWindow.xaml.cs
- **No functional changes**.
- Renamed `parentHwnd` to `ownerHwnd` in `SetOwnership` method for consistency.
Improves code readability and maintainability
**Manually tested**
=> Fix variable naming inconsistency in SetOwnership method

WinUIGallery/Pages/SettingsPage.xaml
Wrapped the `StackPanel` inside a `Border` in the **Settings** page to fix a slight blurriness issue when the main window is maximized.  
- This change improves the visual clarity of items inside the `StackPanel`.
- This was a subtle and hard-to-notice side effect caused by #1791.
- It seems that modifying the visual properties of a `StackPanel` inside a `ScrollView` or `ScrollViewer` can cause rendering issues when the window is maximized.
- Wrapping the StackPanel inside a Border or Grid can help stabilize the rendering.
- Manually tested by maximizing and resizing the window to check for blurriness.  
The difference is subtle and not easily captured in screenshots. The blurriness requires deep observation while maximizing the window to notice it.
=> Fix slight blurriness in Settings StackPanel

WinUIGallery/Samples/Data/ControlInfoData.json
Changed the `ImagePath` for the `RepeatButton` control to use the unused asset located at:  
`"ms-appx:///Assets/ControlImages/RepeatButton.png"`  
The previous image asset path was incorrect (using `Button.png`). This update ensures that the correct image is displayed for the `RepeatButton` control.  
**Manually Tested**
=> Update `RepeatButton` Image Asset Path

WinUIGallery/Samples/ControlPages/AcrylicPage.xaml, WinUIGallery/Samples/ControlPages/AcrylicPage.xaml.cs, WinUIGallery/Samples/Data/ControlInfoData.json
Removed the "Default background acrylic brush" sample from AcrylicPage.xaml.
1. Removed the sample
2. Added a link to the SystemBackdrop sample in the acrylic brush page to help developers find background acrylic.
The Background acrylic brush defaults to in-app acrylic because background acrylic brushes don't exist in winui 3.
Manual
=> Remove background acrylic brush sample

WinUIGallery/Helpers/TabViewHelper.cs, WinUIGallery/Samples/ControlPages/TabViewPage.xaml, WinUIGallery/Samples/ControlPages/TabViewPage.xaml.cs
**Bug** [52757718](https://dev.azure.com/microsoft/OS/_workitems/edit/52757718) Lack of Alternative Single Pointer Method for Tab Movement in TabView Screen.
**Fix** - Adding context menu for the TabView example in the WinUI Gallery which allows the tabs to be moved left and right with single click in addition to the dragging method.
**Testing** - Tested in the WinUI Gallery app. 
**Screenshots** 
**Changes** 
1. **WinUIGallery/Helpers/TabViewHelper.cs** - Added a function PopulateTabViewContextMenu(MenuFlyout contextMenu) 
- Gets the parent tab view and tab view item of the context menu.
- Add left move menu if index > 0 with its action (Adds except 1st item)
- Add right move menu if index < count -1   (Adds except last item)
- Closes the menu if the context menu is empty (To avoid empty …
=> Added the context menu for the tab view for left and right actions.

WinUIGallery/Samples/ControlPages/AppWindowPage.xaml, WinUIGallery/Samples/ControlPages/AppWindowPage.xaml.cs, WinUIGallery/Samples/SampleCode/AppWindow/AppWindowSample2_cs.txt, WinUIGallery/Samples/SampleCode/AppWindow/AppWindowSample5_cs.txt, WinUIGallery/Samples/SampleCode/AppWindow/AppWindowSample6_cs.txt, WinUIGallery/Samples/SamplePages/ModalWindow.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow1.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow2.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow3.xaml, WinUIGallery/Samples/SamplePages/SampleWindow3.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow4.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow6.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow7.xaml.cs
- Added a maximize then restore button.
- Showcased the `TitleBar.PreferredTheme` feature and set it to `UseDefaultAppMode` across all sample windows.
- Demonstrated the `SetTaskBarIcon` and `SetTitleBarIcon` methods.
- Updated the sample code to reflect these enhancements and added explanatory comments for better understanding.
- This change introduces new features from WinAppSDK 1.7.
- Related to this https://github.com/microsoft/WinUI-Gallery/pull/1824#issuecomment-2772781823.
**Manually tested**
=> AppWindow: Add maximize/restore button & showcase new WASDK 1.7 features

WinUIGallery/Samples/ControlPages/AppWindowPage.xaml, WinUIGallery/Samples/ControlPages/AppWindowPage.xaml.cs, WinUIGallery/Samples/ControlPages/PopupPage.xaml, WinUIGallery/Samples/SampleCode/AppWindow/AppWindowSample2_cs.txt, WinUIGallery/Samples/SampleCode/AppWindow/AppWindowSample5_cs.txt, WinUIGallery/Samples/SampleCode/AppWindow/AppWindowSample6_cs.txt, WinUIGallery/Samples/SamplePages/ModalWindow.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow1.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow2.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow3.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow4.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow6.xaml.cs, WinUIGallery/Samples/SamplePages/SampleWindow7.xaml.cs
This PR simplifies the `AppWindow` sample windows logic by removing unnecessary code and making additional changes to improve readability and maintainability.
=> Refactor: Simplify `AppWindow` sample windows logic

WinUIGallery/Helpers/VersionHelper.cs
This PR simplifies SDK versioning by using `ReleaseInfo` and `RuntimeInfo` (new APIs introduced in WinAppSDK 1.7), main changes are:
- Updated `WinAppSdkDetails` to use `ReleaseInfo.AsString`.
- Simplified `WinAppSdkRuntimeDetails` to directly use `RuntimeInfo.AsString`, removing the previous dynamic retrieval logic.
Providing both cleaner code and more complete version details.
=> Update `VersionHelper` for improved SDK version handling

WinUIGallery/App.xaml, WinUIGallery/Samples/ControlPages/Design/IconographyPage.xaml
- Fixed paths for resource files so the WinRT error goes away.
- Minor changes to the Iconography how-to instructions to make them less verbose.
- Minor design tweaks to the Iconography tools: fixed inconsistent spacing and missing borderthickness
=> Fixed resource paths + design tweaks design tool

WinUIGallery/Samples/ControlPages/FlipViewPage.xaml, WinUIGallery/Samples/ControlPages/FlyoutPage.xaml, WinUIGallery/Samples/ControlPages/NumberBoxPage.xaml, WinUIGallery/Samples/ControlPages/RelativePanelPage.xaml, WinUIGallery/Samples/ControlPages/TeachingTipPage.xaml
Adjusted the layout of `ControlExamples` on `FlipViewPage`, `FlyoutPage`, `TeachingTipPage`, `RelativePanelPage`, and `NumberBoxPage` to ensure proper stretching and alignment with the design of other pages.
- Fixes #1855
Manually tested.
=> Fix ControlExamples not stretching properly on multiple pages

WinUIGallery/Helpers/WindowHelper.cs, WinUIGallery/Pages/NavigationRootPage.xaml.cs
This PR removes the `GetAppWindow` method from the `WindowHelper` class and gets the `AppWindow` directly from the window.
=> Remove the GetAppWindow method from the WindowHelper class

WinUIGallery/Models/ControlInfoData.cs
- Clean code.
- Deprecate the old versioning approach.
=> Remove unused constructor from `ControlInfoDocLink` class

WinUIGallery/Samples/SamplePages/SampleSystemBackdropsWindow.xaml.cs
We were not properly respecting high contrast in the Mica Controller sample.
Fixes #1763
Before: See #1763
After:
=> Implement support for high contrast in mica controller sample

tests/WinUIGallery.UITests/AxeHelper.cs, tests/WinUIGallery.UITests/README.md, tests/WinUIGallery.UITests/SampleTestTemplate.cs, tests/WinUIGallery.UITests/SessionManager.cs, tests/WinUIGallery.UITests/TestBase.cs, tests/WinUIGallery.UITests/Tests/AxeScanAllTests.cs, tests/WinUIGallery.UITests/Tests/Button.cs, tests/WinUIGallery.UITests/Tests/CheckBox.cs, tests/WinUIGallery.UITests/Tests/ComboBox.cs, tests/WinUIGallery.UITests/Tests/DatePicker.cs, tests/WinUIGallery.UITests/Tests/MediaPlayerElement.cs, tests/WinUIGallery.UITests/Tests/PersonPicture.cs, tests/WinUIGallery.UITests/Tests/ProgressBar.cs, tests/WinUIGallery.UITests/Tests/RadioButton.cs, tests/WinUIGallery.UITests/Tests/SearchResults.cs, tests/WinUIGallery.UITests/Tests/Slider.cs, tests/WinUIGallery.UITests/Tests/TextBlock.cs, tests/WinUIGallery.UITests/Tests/TextBox.cs, tests/WinUIGallery.UITests/Tests/ToggleButton.cs, tests/WinUIGallery.UITests/Tests/ToggleSwitch.cs, tests/WinUIGallery.UITests/WinUIGallery.UITests.csproj, tests/WinUIGallery.UnitTests/Package.appxmanifest, tests/WinUIGallery.UnitTests/UnitTestApp.xaml, tests/WinUIGallery.UnitTests/UnitTestApp.xaml.cs, tests/WinUIGallery.UnitTests/UnitTestAppWindow.xaml, tests/WinUIGallery.UnitTests/UnitTestAppWindow.xaml.cs, tests/WinUIGallery.UnitTests/UnitTests.cs, tests/WinUIGallery.UnitTests/WinUIGallery.UnitTests.csproj, tests/WinUIGallery.UnitTests/app.manifest
As the title.
Please enable this option to hide space to tab changes.
The code quality in the test projects was not as good and so, improved it to be consistent.
- #1806
- Build the test projects
=> Improved source quality in the test projects

WinUIGallery/Samples/Data/IconsData.json
Added missing icons to the Iconography panel. Also corrected typos in several icon names to ensure consistency with the official Segoe Fluent Icons reference.
https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#icon-list
=> Feat(iconography): add missing icons and fix typos in icon names

WinUIGallery/Samples/Data/IconsData.json
Compared to https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font
=> Missing glyph in IconsData

README.md
This PR updates the README to fix the incorrect Microsoft Store link, which previously pointed to the File app instead of the WinUI 3 Gallery app.
Fixes #1910 
Manually tested the updated link.
=> Fix the wrong Microsoft Store link on README

WinUIGallery/Samples/ControlPages/Fundamentals/BindingPage.xaml
**Bug:** [[WinUI 3 Gallery: Fundamentals -> Binding]: On applying text scaling 200%, the placeholder text of OneWay Binding and TwoWay Binding are getting truncated.](https://microsoft.visualstudio.com/OS/_workitems/edit/58165989)
**Description:**
The placeholder text of the textbox in the binding page is getting truncated when the text scaling is set to 200%.
**Changes:**
Files changed
` WinUIGallery/Samples/ControlPages/Fundamentals/BindingPage.xaml`
Code changes:
`Width="200"` is changed to` MinWidth="380"`
```
<TextBox
x:Name="SourceTextBoxOneWay"
MinWidth="380"
HorizontalAlignment="Left"
PlaceholderText="Enter text here" />
```
**Test:**
Tested in the gallery app. Attached the screenshots for reference.
**Screenshots:**
**Normal State:**
**Text Scaling Set to 200%:**
**Before fix:** …
=> Fix placeholder text truncation for OneWay and TwoWay Binding

WinUIGallery/Samples/SampleCode/TeachingTip/TeachingTipSample1_cs.txt, WinUIGallery/Samples/SampleCode/TeachingTip/TeachingTipSample2_cs.txt, WinUIGallery/Samples/SampleCode/TeachingTip/TeachingTipSample3_cs.txt
Corrected a mismatch between the button name in the XAML and the code-behind file within the Teaching Tip section of the WinUI 3 Gallery app. The button and its associated TeachingTip control now use consistent naming.
This change was required to resolve an inconsistency where the button name in the XAML did not match the reference in the C# code-behind. This caused issues with the TeachingTip functionality. 
Tested by running the WinUI 3 Gallery app and verifying that the TeachingTip now displays correctly when the button is clicked. Checked both the XAML and code-behind to ensure the names are consistent and the TeachingTip is triggered as expected.
XAML
```
<Button
x:Name="TestButton1"
Click="TestButton1Click"
Content="Show TeachingTip" />
<TeachingTip
x:Name="TestButton1TeachingTip" …
```
=> [FIX] Bug in Teaching Tip

WinUIGallery/Samples/ControlPages/TimePickerPage.xaml
Adding the current time on init for TimePicker sample.
Addressing: https://github.com/microsoft/WinUI-Gallery/issues/526
=> Adding current time to TimePicker sample

WinUIGallery/Samples/ControlPages/ScrollViewPage.xaml
This PR improves the text readability on the `ScrollView` page by wrapping it.
You need to resize the app to read the rest of the text.
**Before:**
**After:**
=> Improve text readability on ScrollView page

WinUIGallery/Samples/Data/IconsData.json
This PR updates the *IconsData.json* file by tagging icon entries that belong to the `Symbol` enum. This change complements issue #1880 and aligns with PR #1881.
This makes easier to see the options when using `SymbolIcon`.
=> Tag icon entries using "symbol-icon" for Symbol enum categorization

WinUIGallery/Controls/DesignGuidance/ColorSections/FillSection.xaml, WinUIGallery/Controls/DesignGuidance/ColorSections/TextSection.xaml
**Fixes #1948 :**
Before:
After:
**Fixes #1949
Fixes #1950**
Before:
After:
=> Updating Color overview foreground colors to meet contrast ratios

WinUIGallery/App.xaml.cs, WinUIGallery/Samples/ControlPages/BadgeNotificationManagerPage.xaml, WinUIGallery/Samples/ControlPages/BadgeNotificationManagerPage.xaml.cs, WinUIGallery/Samples/ControlPages/ScrollViewPage.xaml.cs
=> Fix UnPackaged Issues

WinUIGallery/Helpers/TitleBarHelper.cs, WinUIGallery/MainWindow.xaml.cs
When the app theme is set to Light or Dark (not “Use system setting”) and the app theme differs from the system theme, the app initially opens in the system theme and then switches to the chosen app theme.
Previously, the titlebar button colors were not updated during this theme change, resulting in low contrast.
This fix updates the button colors whenever the root grid theme changes and removes the old broken logic.
- Fixes #1605 
- Fixes #1970 
=> Fix: sync titlebar button colors with app theme changes

WinUIGallery/Helpers/TitleBarHelper.cs, WinUIGallery/Samples/ControlPages/TitleBarPage.xaml, WinUIGallery/Samples/ControlPages/TitleBarPage.xaml.cs
The window TitleBar button colors were being changed when navigating to the TitleBar page while the app theme differed from the system theme.
The exact root cause couldn’t be identified, so the button colors were explicitly set in the control’s `LayoutUpdated` event (the last event triggered in the control’s lifecycle).
Setting the colors in the `Loaded` event didn’t work, whereas setting them during `LayoutUpdated` resolved the issue.
- Closes #2022
=> Fix: TitleBar page changing window TitleBar buttons colors

WinUIGallery/Helpers/TitleBarHelper.cs, WinUIGallery/Pages/SettingsPage.xaml.cs, WinUIGallery/Samples/SamplePages/SampleBuiltInSystemBackdropsWindow.xaml.cs, WinUIGallery/Samples/SamplePages/SampleSystemBackdropsWindow.xaml.cs
This PR fixes an issue where setting the app to light mode while system theme is dark would result in over for caption buttons being white on white.
As part of this, I cleaned up the TitleBar helper and switched to one function to be called by everyone instead of the segmented functions.
=> Fix light theme caption button hover, cleanup TitleBarHelper

WinUIGallery/Samples/Data/IconsData.json
Remove deprecated icon `E18A: Placeholder` from IconsData.json.
It's mentioned in the doc below that `E18A: Placeholder` is deprecated.
> [!NOTE]
> Glyphs with prefixes ranging from E0- to E5- (e.g. E001, E5B1) are currently marked as legacy and are therefore deprecated.
>
https://learn.microsoft.com/windows/apps/design/style/segoe-fluent-icons-font#icon-list
See #2008 for context.
Ran the app and checked the changes.
=> Remove deprecated icon (E18A: Placeholder) from IconsData.json

WinUIGallery/Samples/ControlPages/Fundamentals/Controls/ValidatedPasswordBox.cs, WinUIGallery/Samples/ControlPages/Fundamentals/Controls/ValidatedPasswordBox.xaml, WinUIGallery/Samples/SampleCode/CustomUserControls/CustomUserControlsSample2_cs.txt, WinUIGallery/Samples/SampleCode/CustomUserControls/CustomUserControlsSample2_xaml.txt
Main Changes
- Validation messages now update according to the active theme
- `ValidationRichText` is collapsed when no password has been entered
- Updated the sample code accordingly
- Closes #2019
=> Fix Custom PasswordBox validation messages not updating with theme
