microsoft/WinUI-Gallery

XamlControlsGallery/ControlPages/TreeViewPage.xaml, XamlControlsGallery/ControlPagesSampleCode/TreeView/TreeViewDataBindingSample_xaml.txt, XamlControlsGallery/XamlControlsGallery.csproj
Fixing closing brackets
Adding prefix to explicitly reference the Microsoft.UI.Xaml.Controls version of TreeView and TreeViewItem.
Fixes issue #14 
Manual Testing
=> TreeView: Fixing code sample typos

XamlControlsGallery/ControlPages/NavigationViewPage.xaml.cs, XamlControlsGallery/SamplePages/SampleCompactSizingPage.xaml, XamlControlsGallery/SamplePages/SampleStandardSizingPage.xaml
Adding a few missing accessibility names.
Fixing two internally-tracked accessibility bugs.
manually
=> Missing UIA names

XamlControlsGallery/ControlPages/ButtonPage.xaml, XamlControlsGallery/ControlPages/ListViewPage.xaml, XamlControlsGallery/ControlPages/RevealFocusPage.xaml, XamlControlsGallery/ControlPages/RichEditBoxPage.xaml, XamlControlsGallery/ControlPages/ToggleSplitButtonPage.xaml.cs, XamlControlsGallery/ControlPages/TreeViewPage.xaml, XamlControlsGallery/ControlPagesSampleCode/Buttons/Button/CustomButtonStyle.txt, XamlControlsGallery/ControlPagesSampleCode/TreeView/TreeViewTemplateSelectorSample_xaml.txt, XamlControlsGallery/XamlControlsGallery.csproj
Added accessibility names and modified sample code when appropriate to fix bugs tracked internally.
- added missing automation names
- updated sample code to match xaml
- for Last TreeView sample, fixed code sample with poor formatting
Internal bugs, as noted in each commit.
=> Add missing UIA names

XamlControlsGallery/Common/ActivityFeedLayout.cs, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
This updates the repeater sample and custom layout example now that most of the API is finalized and available in the latest prerelease Nuget package.
=> Enable ItemsRepeater sample w/ latest prerelease package

XamlControlsGallery/ControlPages/RichEditBoxPage.xaml, XamlControlsGallery/ControlPages/ThemeTransitionPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample2_xaml.txt, XamlControlsGallery/ControlPagesSampleCode/Text/RichEditBox/RichEditBoxSample4_xaml.txt
Added missing UIA names to text boxes and made list item names unique.
Updated app code and sample markup when appropriate.
Internal bugs
manually verified
=> Fixing accessibility names

XamlControlsGallery/DataModel/ControlInfoData.json
Updated Pivot's Guidelines link. 
Resolved Issue #50
Manually tested link to ensure appropriate direction to Pivot's Guidelines documentation.
=> Resolved Issue #50 by updating Pivot's Guidelines link.

XamlControlsGallery/ControlPages/MenuBarPage.xaml, XamlControlsGallery/ControlPagesSampleCode/MenuBar/MenuBarSample1.txt, XamlControlsGallery/ControlPagesSampleCode/MenuBar/MenuBarSample2.txt, XamlControlsGallery/DataModel/ControlInfoData.json
Updated MenuBar sample to include RadioMenuFlyoutItem
- Added MenuBarItem with two RadioMenuFlyoutItemGroups
- Corrected namespace to 'muxc'
- Updated code files to show namespace when appropriate
- Changed status of MenuBar sample from New to Updated
- Fixed related control links
Provide sample of new control: https://github.com/Microsoft/microsoft-ui-xaml/issues/173
=> RadioMenuFlyoutItem sample code

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/PageHeader.xaml, XamlControlsGallery/XamlControlsGallery.csproj
Thankfully the Xaml Controls Gallery doesn't have any samples for things under preview so I'm able to easily switch from the preview to the staged release package.
This includes a couple of API renames as well.
=> Retarget to release WinUI nuget package

XamlControlsGallery/ControlPages/TeachingTipPage.xaml.cs, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs, XamlControlsGallery/PageHeader.xaml.cs
Fix the TeachingTip sample bug.
#81 
Testing environment : 17763
Manual verification.
=> Fix the TeachingTip sample bug.

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml, XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Add sample usage of the new ScrollViewer control
Bump the target platform version
Reference a more recent drop of WinUI
Fix-up the ItemsRepeater page to compile with a newer drop of WinUI that has the renamed type
Fix the doc link for ItemsRepeater
Build and launched debug version of the app
Opened the ItemsRepeater page and verified "Guidelines" link opens a valid page
Opened the new ScrollViewer sample, toggled the various properties to ensure they work, and validated that the links open expected doc pages.
=> Sample for new ScrollViewer control

XamlControlsGallery/ControlPages/TextBoxPage.xaml
=> Documentation Fix; `TextBlock` -> `TextBox`

README.md, XamlControlsGallery/ControlPages/RichTextBlockPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json
Change the rest of the old MSDN links to docs. Add link to VS 2019.
=> Change remaining MSDN links to Docs.

.github/ISSUE_TEMPLATE/bug_report.md
Adds May 2019 Update to Windows 10 Version options
=> Add May 2019 Update target version to bug template

XamlControlsGallery/SettingsPage.xaml
Updates dependencies list in settingspage.xaml to:
* Update WinUI link and text since it's no longer using a preview version
* Add missing dependencies
* Remove unnecessary extra RichTextBlock
=> Update dependencies list in settings page

UITests/Button.cs, UITests/CheckBox.cs, UITests/ComboBox.cs, UITests/DatePicker.cs, UITests/Media.cs, UITests/ProgressBar.cs, UITests/Properties/AssemblyInfo.cs, UITests/README.md, UITests/RadioButton.cs, UITests/SampleTestTemplate.cs, UITests/Slider.cs, UITests/TextBlock.cs, UITests/TextBox.cs, UITests/ToggleButton.cs, UITests/ToggleSwitch.cs, UITests/UITestSettings.runsettings, UITests/UITests.csproj, UITests/UITests.sln, UITests/app.config, UITests/base.cs, UITests/packages.config
Added WinAppDriver UI tests to be used in CI.
Running UI tests in CI using Azure Pipelines will help catch potential deployment issues or UI bugs. 
Tested using my own DevOps instance with test case passing (see image below).
=> WinAppDriver UI Tests

XamlControlsGallery/ControlPages/CommandBarFlyoutPage.xaml, XamlControlsGallery/ControlPagesSampleCode/CommandBarFlyout/CommandBarFlyoutSample1_xaml.txt
Added tooltips to CommandBarFlyout sample and updated sample code.
There's no way to expand the primary commands to show their labels, and having icons without labels goes against our best practices.
Manually verified.
=> CommandBarFlyout tooltips

XamlControlsGallery/ControlPages/AcrylicPage.xaml
Code snippet was not correct/matching with resource name. See issue #119 
Type in code snippet text.
Was incorrect and causing issues when copy-pasting from snippet into app.
Now copy-pastes correctly.
=> Update In app acrylic code snippet

XamlControlsGallery/ItemPage.xaml, XamlControlsGallery/Strings/en-US/Resources.resw
Updated the page template for samples to include a feedback link: https://github.com/microsoft/Xaml-Controls-Gallery/issues/new/choose
Added new feedback panel block and modified visual states to show appropriate layout. Hardcoded the link to point to a constant URL.
#118 
Manually verified at different window widths.
=> Added link to GitHub

XamlControlsGallery/ControlPages/NavigationViewPage.xaml, XamlControlsGallery/ControlPages/NavigationViewPage.xaml.cs
Added interactive code snippet for the last sample on the NavigationView page.
Used ControlExample.Xaml control to show code sample. The only options check box not wired correctly in the sample is "Autosuggestbox visible" because I couldn't figure out a good property to bind to.
Also updated the namespace title from *muxcontrols* to *muxc*.
#42
=> Added code to NavigationView API in action sample

XamlControlsGallery/ControlPages/MenuFlyoutPage.xaml
Fixed a typo in the MenuFlyout code sample
Fixes #38
=> Fixe typos in MenuFlyout page; Closes #38;

XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs
Added lorem ipsum text to RichEditBox to make it easier to test out the splitbutton.
Added calling of RichEditBox.Document.SetText() add initialization of Page.
Fixes #95.
Tested by manually starting application.
=> Add lorem ipsum text to splitbutton page; Closes #95;

XamlControlsGallery/ControlPages/InkCanvasPage.xaml
Added header for toggle button on InkCanvas page.
Added the header "Shape to draw" to the toggle button.
Fixes #167.
Tested by navigation through InkCanvas page using narrator in item mode.
=> Add header for shape toggle button on InkCanvas page; Closes #167;

XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml
Added tooltips to buttons in AnimatedVisualPlayer page.
Added the respective tooltips to the buttons in the AnimatedVisualPlayer page.
Fixes #170.
Tested manually by tabbing through buttons.
=> Add tooltips to buttons in AnimatedVisualPlayer; Closes #170;

XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml
Add missing list name
Added AutomationProperties.Name property to list.
Fixes #183.
Tested manually by navigating through page with narrator in item mode
=> Add missing list name; Closes #183:

XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml
Add missing slider names
Added AutomationProperties.Name property to sliders.
Fixes #185.
Tested manually by navigating through page with narrator in item mode
=> Add missing slider names; Closes #185

XamlControlsGallery/ControlPages/ScrollViewer2Page.xaml
Added missing combo box names;
Added AutomationProperties.Name property to comboboxes.
Fixes #186.
Tested manually by navigating through page with narrator in item mode
=> Add missing combo box names; Closes #186;

XamlControlsGallery/ControlPages/ToolTipPage.xaml
Added a sample for the PlacementRect property of the ToolTip.
Removed an offset in the second sample that was ignored.
Added a new sample to the ToolTip sample page for the PlacementRect property
Closes #180
Tested manually by starting application and hovering over the items in question
=> Add sample for PlacementRect, Remove ignored offset, Closes #180

XamlControlsGallery/ItemPage.xaml
Added tooltips for the documentation and feedback links on the control pages
Closes #207.
Tested by starting application and hovering over the links in question.
=> Add tooltips for hyperlinks on control sample pages

XamlControlsGallery/ControlPages/ColorPickerPage.xaml
Switch to WinUI Colorpicker
Fixes #214 
Tested manually by starting application and navigating to ColorPicker page.
=> Switch to WinUI Colorpicker

XamlControlsGallery/ControlPages/DropDownButtonPage.xaml, XamlControlsGallery/ControlPages/SplitButtonPage.xaml, XamlControlsGallery/ControlPages/SplitButtonPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/Buttons/DropDown/DropDownButton_RevealStyle.txt, XamlControlsGallery/ControlPagesSampleCode/Buttons/SplitButton/SplitButtonSample2.txt, XamlControlsGallery/XamlControlsGallery.csproj
Add new samples for the RevealStyle applied to SplitButton and DropDownButton
Closes #155 
=> Add RevealStyle sample for Split- and DropDownbutton

XamlControlsGallery/ControlPages/NavigationViewPage.xaml.cs
Added a "UpdatyLayout" as the NavigationView in question is partially in the right state and partially not. So updating the layout fixes it.
Fixes #218 
Tested by using XCG in full screen mode (large enough that the NavVIew is in top-displaymode) and navigating to and from the NavigationView test page.
=> Fix bug where the "Dynamic displaymode sample" would not work correctly

UITests/Media.cs
=> Update Media.cs UI Tests

XamlControlsGallery/ControlPages/MenuFlyoutPage.xaml
Updated the MenuFlyouts sample code to correctly match the samples.
Fixes #226 
=> Update MenuFlyout sample code

XamlControlsGallery/DataModel/ControlInfoData.json
Change IsNew and IsUpdated metadata.
@stmoy, I wasn't sure what to do with the motion pages and would particularly appreciate your thoughts. 
fixes #140 
manually verified
=> Updated IsNew and IsUpdated status of pages.

README.md
=> Update notes about winui3alpha

XamlControlsGallery/AllControlsPage.xaml, XamlControlsGallery/NewControlsPage.xaml, XamlControlsGallery/PageHeader.xaml, XamlControlsGallery/PageHeader.xaml.cs
Added a DropShadow behind header text that sits on top of the hero image to improve legibility.
The DropShadow code was copied almost verbatim from https://docs.microsoft.com/en-us/windows/uwp/composition/using-the-visual-layer-with-xaml#drop-shadow. Made sure the shadow is drawn when the title text is over an image. The shadow hides on scrolling and does not appear on other pages (without a header background image). 
Right now, the narrowest app width doesn't show shadow behind its title text because I didn't want to add the same dropshadow code to more pages for an app state I hope to rework.
This is a proof of concept for a new design pattern @chigy is investigating.
Manually verified in light/dark theme and at different app widths.
=> Added shadow behind text

XamlControlsGallery/XamlControlsGallery.csproj
Fixing build error which may have resulted from a bad merge.
=> Fixing build error

XamlControlsGallery/XamlControlsGallery.csproj
Think this may have gotten messed up in the merge conflict. New ListView sample code files weren't being included in the .csproj files.
=> Added back ListView samples to .csproj file

XamlControlsGallery/DataModel/ControlInfoData.json
Now that we display Subtitles in the control cards, I took a pass on the content. I standardized the wordings, added periods, and added a subtitle where one was not present before.
Previously the subtitles were only displayed on the control pages themselves. Now that they appear on the tiles, I wanted to ensure that they looked alright.
Manual.
=> Minor cleanup to subtitles

XamlControlsGallery/ControlPages/GridViewPage.xaml
Fixed this bug: https://microsoft.visualstudio.com/OS/_workitems/edit/24094717?src=WorkItemMention&src-action=artifact_link
Tested screenreader with AccessibilityInsights
=> GridView layout sample: Added AutomationProperties.Name to textboxes

XamlControlsGallery/ControlPages/RadioButtonPage.xaml, XamlControlsGallery/ControlPages/TreeViewPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Change from StackPanel to RadioButtons to demonstrate the improved keyboarding and accessibility experience.
=> Move RadioButton sample pages onto RadioButtons

XamlControlsGallery/DataModel/ControlInfoData.json
- Removes link to InkToolbar related control because that page doesn't exist
- Adds link to InkToolbar API doc
Fixes #296 
Built and run locally
=> Remove InkToolbar sample reference, add API reference

XamlControlsGallery/ControlPagesSampleCode/GridView/GridViewSample1_xaml.txt
Fixed bug #293 
#293 , I think there should be a "/" character (closing tag).
Checked manually.
=> Added missing closing tag in GridView example.

XamlControlsGallery/ControlPages/AutomationPropertiesPage.xaml, XamlControlsGallery/ControlPages/AutomationPropertiesPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
This PR will add a page containing samples around AutomationProperties, which are useful (and needed) to write accessible XAML.
Closes #199 
=> Add AutomationProperties page

XamlControlsGallery/XamlControlsGallery.csproj
Updates the WinUI Nuget package version to latest 2.3 release. 
Several PRs (#279, #274) are targeting different versions of WinUI. Lets snap to the latest release version.
Manual
=> Update to latest WinUI 2.3 release package

XamlControlsGallery/ControlPages/InkToolbarPage.xaml, XamlControlsGallery/ControlPages/InkToolbarPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Adds the missing InkToolbar page.
Fixes #297 
=> Add InkToolbar page

XamlControlsGallery/DataModel/ControlInfoData.json
Replaced the ComboBox guideline link with the correct link.
Fixes #310 
Tested manually by starting app and clicking on link.
=> Replace wrong ComboBox guideline link with correct one

XamlControlsGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample3.txt
Adaptive Triggers only work when placed inside first component of a Page. The adaptive triggers sample used on the NavigationView page should indicate that.
Fixes #287
=> Improve NavigationView AdaptiveTrigger code sample

XamlControlsGallery/ControlPages/ListViewPage.xaml, XamlControlsGallery/ControlPages/ListViewPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/ListView/ListViewSample4_cs.txt, XamlControlsGallery/ControlPagesSampleCode/ListView/ListViewSample4_xaml.txt, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Added a new sample to the ListView page that allows users to see how a ListView can be filtered using three textboxes, each representing a different filter.
Tested manually using one, two, and all filters. 
- [ x ] New feature (non-breaking change which adds functionality)
=> Add filtering sample to ListView page

XamlControlsGallery/XamlControlsGallery.csproj
Updating microsoft.ui.xaml reference to the latest 2.4 prerelease which includes these updates..
https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0-prerelease.200113001
=> update to latest 2.4 prerelease version of microsoft.ui.xaml

XamlControlsGallery/ControlPages/AutomationPropertiesPage.xaml, XamlControlsGallery/ControlPages/AutomationPropertiesPage.xaml.cs
Removed binding and handle value change manually
Fixes #324 
Tested by reproducing steps in #324
=> Fix crash when clearing Numberbox

XamlControlsGallery/CollectionsInterop.cs, XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml, XamlControlsGallery/ControlPages/WebView2Page.xaml, XamlControlsGallery/ControlPages/WebView2Page.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/Package.appxmanifest, XamlControlsGallery/XamlControlsGallery.csproj
XamlControlsGallery updates for alpha2 - add WebView2 scenario + refresh updated/new + some minor cleanup.
=> XamlControlsGallery changes for Alpha (February 2020)

XamlControlsGallery/ControlPages/AutomationPropertiesPage.xaml
Put text in the "Text" property of TextBlock for performance, and add text wrapping.
Fixes #330
=> Fix issue with text not wrapping on AutomationProperties page

.github/ISSUE_TEMPLATE/bug_report.md
Windows 1909 is missing, so lets add it.
=> Add missing windows version

XamlControlsGallery/ControlPages/PageTransitionPage.xaml.cs
Fix faulty drillin check.
Fixes #321
=> Fix issue with DrillIn animation not being applied

UITests/ProgressBar.cs
Switch the UIA name we need for the "increase progressbar value" button to the correct one.
Fixes #346 
Ran UI tests locally
=> Fix CI test failures because of switch to NumberBox

XamlControlsGallery/ControlPagesSampleCode/TeachingTip/TeachingTipSample1_xaml.txt, XamlControlsGallery/ControlPagesSampleCode/TeachingTip/TeachingTipSample2_xaml.txt, XamlControlsGallery/ControlPagesSampleCode/TeachingTip/TeachingTipSample3_xaml.txt
Switch namespace in TeachingTip sample code
Fixes #280 
Tested by starting app and looking at source code.
=> Switch namespaces in teachingtip sample to muxc

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json
Adding links to UniformGridLayout and StackLayout APIs as these are mentioned in the samples.
Addresses issue #369.
Tested to make sure links work.
=> Add links to ItemsRepeater page

XamlControlsGallery/XamlControlsGallery.csproj
Updating Microsoft.UI.Xaml to latest prerelease version [2.4.0-prerelease.200322001](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0-prerelease.200322001)
=> Updating Microsoft.UI.Xaml to latest prerelease version 2.4.0-prerelease.200322001

XamlControlsGallery/ControlPages/TabViewPage.xaml, XamlControlsGallery/ControlPages/TabViewPage.xaml.cs
This PR adds the samples shown in the WinUI community call.
Showcase the new features.
=> This PR adds the demos from the WinUI community call

XamlControlsGallery/ControlPages/ButtonPage.xaml, XamlControlsGallery/ControlPages/RevealPage.xaml
Changed content of button samples so that they are not announced as "Button, Button".
Closes #380 
Tested using narrator.
=> Rename buttons to be more accessible for people using narrator

XamlControlsGallery/ItemPage.xaml, XamlControlsGallery/ItemPage.xaml.cs
Using the page type name, we generate the GitHub source code link and display a link to the C# code and the XAML code.
Closes #391 
Tested by viewing links of some pages (all worked)
@MikeHillberg I hope that is what you had in mind. Otherwise please let me know what can be better.
=> Add source code links to item pages

XamlControlsGallery/SettingsPage.xaml
Added a link to the official Microsoft Fluent XAML Theme Editor app under the companion apps section.
It's a great app and made by the Microsoft XAML dev team.
=> Added the link to the Fluent XAML Theme Editor

XamlControlsGallery/ControlPagesSampleCode/ListView/ListViewSample2_cs.txt
Add setting of source on the ListView Grouped headers sample
Closes #397
=> Add missing code in ListView sample code

XamlControlsGallery/ControlPages/BorderPage.xaml, XamlControlsGallery/ControlPages/CompactSizingPage.xaml, XamlControlsGallery/ControlPages/ConnectedAnimationPage.xaml, XamlControlsGallery/ControlPages/ConnectedAnimationPage.xaml.cs, XamlControlsGallery/ControlPages/EasingFunctionPage.xaml, XamlControlsGallery/ControlPages/GridViewPage.xaml, XamlControlsGallery/ControlPages/ImagePage.xaml, XamlControlsGallery/ControlPages/InkCanvasPage.xaml, XamlControlsGallery/ControlPages/InkToolbarPage.xaml, XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml, XamlControlsGallery/ControlPages/NavigationViewPage.xaml, XamlControlsGallery/ControlPages/NumberBoxPage.xaml, XamlControlsGallery/ControlPages/PageTransitionPage.xaml, XamlControlsGallery/ControlPages/PersonPicturePage.xaml, XamlControlsGallery/ControlPages/ProgressBarPage.xaml, XamlControlsGallery/ControlPages/RevealFocusPage.xaml, XamlControlsGallery/ControlPages/StackPanelPage.xaml, XamlControlsGallery/ControlPages/VariableSizedWrapGridPage.xaml, XamlControlsGallery/ControlPages/ViewBoxPage.xaml, XamlControlsGallery/ControlPages/XamlCompInteropPage.xaml, XamlControlsGallery/ControlPages/XamlCompInteropPage.xaml.cs
This switches all control pages to the new RadioButtons control for better accessibility
Fixes #336 
Tested manually by checking functionality of modified pages.
=> Switch to radiobuttons

XamlControlsGallery/SettingsPage.xaml, XamlControlsGallery/SettingsPage.xaml.cs
The Gallery didn't have a good way for folks to file new bugs or request samples directly from the app. This change adds links back to GitHub. 
This change also removes the "email us" link because we'd prefer to connect over GitHub.
Also also remove the hidden feedback button which was hidden and didn't do anything.
Manual testing
=> Add links to GitHub

XamlControlsGallery/ControlPages/TabViewPage.xaml.cs, XamlControlsGallery/XamlControlsGallery.csproj
Updating WinUI version to[ latest pre-release. ](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0-prerelease.200422001)
=> Update WinUI to latest pre-release bits.

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Switch to using latest stable WinUI version
=> Update WinUI version

XamlControlsGallery/ControlPages/FlipViewPage.xaml
Remove duplicate `"` to make XAML valid again.
Closes #421 (and removes the typo, yay 🎉)
=> Fix typo in FlipView sample

XamlControlsGallery/ControlPages/RadialGradientBrushPage.xaml
Add small change value to sliders so they are usable with arrow keys.
Fixes #426 
=> Add smallchange value to sliders on RadialGradientBrush page

XamlControlsGallery/DataModel/ControlInfoData.json
The text for XAMLUICommand and StandardUICommand are a bit misleading, so this PR updates those texts.
Updated description of the controls listed above.
Fixes #433
=> Fix confusing descriptions of XAMLUICommand and StandardUICommand

XamlControlsGallery/ControlPages/InputValidationPage.xaml
Simple typo in sample page. No functional effect. Ported from [issue 1025 in the UWP Samples repo](https://github.com/microsoft/Windows-universal-samples/pull/1025).
=> Typo on InputValidationPage

XamlControlsGallery/SettingsPage.xaml, XamlControlsGallery/SettingsPage.xaml.cs
Improves the way the users can choose whether they want to use top navigation or left navigation.
Closes #436
@Poopooracoocoo What do you think about this change below?
=> Improve NavigationPosition option on settings page

XamlControlsGallery/ControlPages/ToggleSwitchPage.xaml
Fixes #285
Update Control Example so sample code reflects switch
Used ControlExample Substitutions to bind toggle switch.
=> Toggle Switch using ControlExampleSubstitution

XamlControlsGallery/DataModel/ControlInfoData.json
Move RadialGradientBrush to styles section
Closes #484 
=> Move RadialGradientBrush to Styles

XamlControlsGallery/Navigation/NavigationRootPage.xaml, XamlControlsGallery/Navigation/NavigationRootPage.xaml.cs
Adds keyboard accelerator and logic necessary to make Ctrl+F focus the search box
Closes #487
=> Add keyboard accelerator

XamlControlsGallery/ControlPages/TextBlockPage.xaml
Improves styled TextBlock sample
Closes #492
=> Improve styled textblock sample

XamlControlsGallery/XamlControlsGallery.csproj
Update WinUI version to the latest pre-release - [2.5.0-prerelease.200708003](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.5.0-prerelease.200708003).
=> Update WinUI prerelease version to latest

XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml, XamlControlsGallery/ControlPages/AnimatedVisualPlayerPage.xaml.cs
Ported the rejected changes of https://github.com/windows-toolkit/Lottie-Windows/pull/306
Improve sample even further
=> Improve AnimatedVisualPlayer sample

XamlControlsGallery/ControlPages/RichTextBlockPage.xaml, XamlControlsGallery/ControlPages/RichTextBlockPage.xaml.cs
Adds sample for using TextSelectionHighlighters.
Closes #368 
Tested manually by starting app and viewing sample.
=> Add texthighlighter RichTextBlock sample

XamlControlsGallery/XamlControlsGallery.csproj
We just published a new WinUI Prerelease package, this updates XCG to the latest
=> Update the Winui version to the newest prerelease

README.md
It's called Windows UI Library. Windows UI Toolkit could be confusing for developers, as there's a Windows Community Toolkit.
=> Change Windows UI Toolkit to Windows UI Library

XamlControlsGallery/ControlPages/AutoSuggestBoxPage.xaml, XamlControlsGallery/ControlPages/AutoSuggestBoxPage.xaml.cs
The AutoSuggestBox sample now searches a wonderful list of cats and shows "No items found" when there was not a match to align with the official AutoSuggestBox docs.
Closes #509
=> Update AutoSuggestBox sample to be more illustrative

XamlControlsGallery/XamlControlsGallery.csproj
Updating microsoft.ui.xaml package to latest[ pre-release 2.5.0-prerelease.201027002](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.5.0-prerelease.201027002)
=> update muxc to latest pre-release version

XamlControlsGallery/ControlPages/NavigationViewPage.xaml, XamlControlsGallery/ControlPages/NavigationViewPage.xaml.cs, XamlControlsGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample9_xaml.txt, XamlControlsGallery/XamlControlsGallery.csproj
Added a sample on the NavigationView page to show off the new FooterMenuItems feature, coming in WinUI 2.5. More info on this feature can be found in [the spec](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/NavigationView/BottomItems/BottomMenuItems.md).
As a part of releasing this feature, it should have a corresponding sample. 
Just tested manually by me, using mouse, touch, and keyboard in light and dark modes.
=> Adding a sample for FooterMenuItems

XamlControlsGallery/ControlPages/InfoBarPage.xaml, XamlControlsGallery/ControlPages/InfoBarPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Add InfoBar control sample for WinUI 2.5 release. More info about this feature can be found in the [spec](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/gabilka/infobar/active/InformationBar/InformationBar.md)
Closes #597 
Manually tested by me using mouse and keyboard.
=> Add InfoBar Sample

XamlControlsGallery/ControlPages/AcrylicPage.xaml, XamlControlsGallery/ControlPages/RevealPage.xaml
Add text at the top of acrylic and reveal page to explain when fallback is used.
There does not seem to be a document on reveal fallback behavior, was that missed or did I simply not find it @licanhua ?
Closes #553
Visit page and click link.
=> Add text regarding material fallbacks

XamlControlsGallery/ControlPages/ColorPickerPage.xaml, XamlControlsGallery/ControlPages/ColorPickerPage.xaml.cs
Add new radiobuttons to allow users to switch between ring and box spectrum shape.
Improve sample, closes #510 
Tested manually by switching between modes.
=> Add colorspectrum shape to sample

XamlControlsGallery/ControlPages/FlipViewPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json
Update the flip view page to include a vertical example.
Closes #511  
Manual tests
=> Add vertical flip view example.

XamlControlsGallery/XamlControlsGallery.csproj
Update to[ latest WinUI 2.5 pre-release](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.5.0-prerelease.201127001).
=> update WinUI package to latest 2.5 pre-release

XamlControlsGallery/XamlControlsGallery.csproj
Update WinUI version to 2.5 stable.
=> Update to stable WinUI stable 2.5 version

XamlControlsGallery/ControlPages/ProgressBarPage.xaml
Set value on NumberBox to 0 so you don't have to enter a value to be able to use spinbuttons
Closes #534 
=> Update numberbox on determinate progressbar sample to make it better to use

XamlControlsGallery/ControlPages/ProgressRingPage.xaml
All the required information are in the issues
Typo
I don't think testing is required
Check the issue
=> Fix #620 (typo in ProgressRing example)

XamlControlsGallery/ControlPages/PipsPagerPage.xaml, XamlControlsGallery/ControlPages/PipsPagerPage.xaml.cs, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.csproj
Add PipsPager sample, check out [spec PR](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/104) for most up to date information.
=> Add PipsPager Sample Pages

XamlControlsGallery/XamlControlsGallery.csproj
Update WinUI package to [latest 2.6 pre-release](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.6.0-prerelease.210217002).
=> Update WinUI package version to latest pre-release

XamlControlsGallery/XamlControlsGallery.csproj
Updating WinUI to latest pre-release version - 
https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.6.0-prerelease.210315002
=> update WinUI version to latest preview

XamlControlsGallery/DataModel/ControlInfoData.json
Updating the links on the WebView2 page to point to more up-to-date, relevant info. 
The links were outdated (linked to spec rather than official API doc).
Tested locally on my own machine
=> Updating links on WebView2 page

XamlControlsGallery/SamplePages/SampleStandardSizingPage.xaml
Updates the standard size header to read "Standard Size"
Fixes #686
=> Update non compact sample page header

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs
Fix build break due to missing variable declaration/includes.
=> fix build break

XamlControlsGallery/DataModel/ControlInfoData.json
Removed guidance entry from data model file. 
closes #723/#727
manually
=> Remove broken guidance link from AnimatedIcon page

XamlControlsGallery/DataModel/ControlInfoData.json
Removed broken expander guidelines link.
closes #742
manually
=> Fix broken guidelines link from expander page

XamlControlsGallery/XamlControlsGallery.csproj
Updates the XCG to use WinUI 2.6.1.
Fixes #738 
Tested locally on x86 and x64
=> Updating to WinUI 2.6.1

XamlControlsGallery/AllControlsPage.xaml, XamlControlsGallery/App.xaml, XamlControlsGallery/ItemPage.xaml, XamlControlsGallery/ItemsPageBase.cs, XamlControlsGallery/NewControlsPage.xaml, XamlControlsGallery/PageHeader.xaml, XamlControlsGallery/SettingsPage.xaml
- Fix Minimal mode margins
- Update Fonts for consistency
- Adjust SeeAlsoPanel and header margins
visual verification
=> Layout Updates

XamlControlsGallery/ControlPages/ItemsRepeaterPage.xaml.cs, XamlControlsGallery/XamlControlsGallery.csproj
Updated to WinUI 2.7-prerelease package.
=> update version to 2.7 prerelease

XamlControlsGallery/ControlPages/ColorPickerPage.xaml, XamlControlsGallery/ControlPages/ColorPickerPage.xaml.cs
Update ColourPicker control example options to include orientation as a modifier.
=> Add Horizontal ColourPicker Sample to XCG

XamlControlsGallery/standalone.props
Updating the WinUI 3 branch to use 0.8.2, the latest servicing release of WinUI3/Windows App SDK.
=> Updating to 0.8.2

XamlControlsGallery/ControlPages/PersonPicturePage.xaml
Use muxc:PersonPicture instead of wuxc:PersonPicture
=> Use muxc:PersonPicture

XamlControlsGallery/ControlPages/BreadcrumbBarPage.xaml, XamlControlsGallery/ControlPages/BreadcrumbBarPage.xaml.cs
Add BreadCrumbBar sample with custom dataTemplate and appropriate bindings.
=> Add DataTemplate Sample to BreadCrumBarPage

XamlControlsGallery/ControlPages/ProgressBarPage.xaml
Add AutomationProperties.Name to NumberBox to pass all Accessibility Insights test
Fixes #325
=> Add AutomationProperties.Name to NumberBox

XamlControlsGallery/ControlPages/PullToRefreshPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json
Better reflects that this control is touch-centered
=> Updated the description of the pull to update control

XamlControlsGallery/ControlPages/InfoBadgePage.xaml
Fix incorrect xaml code in InfoBadge section
Related to #822 
Similar to #817 
See #822 
Fixed Front Code:
```diff xml
<Button Padding="0" Width="200" Height="60" HorizontalContentAlignment="Stretch" VerticalContentAlignment="Stretch">
<Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Width="Auto" Height="Auto">
-        <SymbolIcon Symbol="Sync" HorizontalAlignment="Center"InfoBadgeStyle}" />
+        <SymbolIcon Symbol="Sync" HorizontalAlignment="Center" Style={StaticResource InfoBadgeStyle}" />
<muxc:InfoBadge Background="#C42B1C" HorizontalAlignment="Right" VerticalAlignment="Top"/>
<muxc:InfoBadge.IconSource>
<muxc:FontIconSource FontFamily="Segoe MDL2 Assets" Glyph="" />
</muxc:InfoBadge.IconSource>
</muxc:InfoBadge>
</Grid>
</Button>
```
Fix back code ([code …
=> Fix broken xaml code

XamlControlsGallery/ControlPages/InfoBadgePage.xaml
=> Fix incorrect xaml source code in InfoBadgePage.xaml

XamlControlsGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample4_cs.txt
The C# sample code contained non existent NavigationView API's, this is fixed now.
Closes #833 
=> Fix faulty C# sample code for NavigationView sample

XamlControlsGallery/Controls/ControlExample.xaml, XamlControlsGallery/Controls/ControlExample.xaml.cs, XamlControlsGallery/Controls/SampleCodePresenter.xaml, XamlControlsGallery/Controls/SampleCodePresenter.xaml.cs
This PR adds a separator between the two code sample languages and moves the copy button on the same height as the sample code titles.
=> Add separator between code samples, update code copy button to be on title line

XamlControlsGallery/SettingsPage.xaml.cs
This PR removes some dead inside the SettingsPage class.
Closes #866 
Ran the app manually.
=> Remove dead code in settingspage class

XamlControlsGallery/ControlPages/BreadcrumbBarPage.xaml
=> Fix BreadcrumbBar opening tag in exapmle

XamlControlsGallery/standalone.props
CsWinRT contains numerous performance improvements.
=> Update WinUI (1.0.3) and CsWinRT versions (1.6.1)

XamlControlsGallery/ControlPages/PipsPagerPage.xaml
Fixing a file that should have been included in #918
=> Adding a fix left off of #918

XamlControlsGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
This PR ports the changes from PR #874 into the WinUI 3 version
=> Port changes from PR #874 (tabview tear out fixes)

XamlControlsGallery/Controls/ControlExample.xaml, XamlControlsGallery/Controls/ControlExample.xaml.cs, XamlControlsGallery/Controls/SampleCodePresenter.xaml, XamlControlsGallery/Controls/SampleCodePresenter.xaml.cs
Port changes from #854 to WinUI 3 branch.
=> Port PR #854 (code separator)

XamlControlsGallery/ControlPages/BreadcrumbBarPage.xaml
=> Fix BreadcrumbBar opening tag in example (#906)

XamlControlsGallery/SettingsPage.xaml.cs
This PR ports the code cleanup from #875 to the WinUI 3 app.
=> Port changes from PR #875 (code cleanup)

XamlControlsGallery/ControlPages/PipsPagerPage.xaml.cs
=> Fixed bug in Pipspager page where images were not showing

XamlControlsGallery/AllControlsPage.xaml, XamlControlsGallery/ControlPages/ImplicitTransitionPage.xaml, XamlControlsGallery/ControlPages/PipsPagerPage.xaml, XamlControlsGallery/DataModel/ControlInfoData.json, XamlControlsGallery/XamlControlsGallery.DesktopWap.Package.wapproj, XamlControlsGallery/XamlControlsGallery.DesktopWap.csproj, XamlControlsGallery/standalone.props
Provide a default TargetFrameworkMoniker based on the version of VS
Fix the AppxBundle warning.
Sync IsUpdated values
Whitespace
=> Fix project TargetFramework

WinUIGallery/ControlPages/CustomTitlebarPage.xaml, WinUIGallery/ItemPage.xaml.cs, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/SearchResultsPage.xaml.cs
Fix the titlebar so that the custom titlebar page properly restores the custom bar (not the fallback).
Fix the crash when a search term is input that yields no results.
=> Fix titlebar and Invalid Search bugs

WinUIGallery/ControlPagesSampleCode/ContentDialog/ContentDialogSample1_cs.txt, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/Package.MSIX.appxmanifest, WinUIGallery/Package.Universal.appxmanifest, WinUIGallery/Package.WAP.appxmanifest
Fix publishing names to match what is expected by the store.
Use both new and old urihandlers for compatibility in case the old was used for automation.
=> Publishing metadata update

WinUIGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample5.txt, WinUIGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample5_xaml.txt
Fix the sample to use the correct attribute
This fixes issue #915. 
The sample was compared against the source
=> fix MenuItemsSource in navigationviewsample

WinUIGallery/Helper/ProtocolActivationClipboardHelper.cs, WinUIGallery/Package.MSIX.appxmanifest, WinUIGallery/Package.Universal.appxmanifest, WinUIGallery/Package.WAP.appxmanifest
=> Update protocol launcher to work with doc pages

WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/NewControlsPage.xaml
=> Removed UWP links

WinUIGallery/ControlPages/ContentDialogPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/ContentDialog/ContentDialogSample1_cs.txt
=> DefaultContentDialogStyle for ContentDialog

WinUIGallery/NewControlsPage.xaml, WinUIGallery/standalone.props
Update the app from preview3 to the GA release of WinAppSDK 1.1.
(Also fix two more URLs that were hard-coded to English)
=> Update to WinAppSDK 1.1

WinUIGallery/Package.WAP.appxmanifest, WinUIGallery/WinUIGallery.DesktopWap.Package.wapproj, WinUIGallery/standalone.props
=> Update to WASDK 1.1

WinUIGallery/App.xaml
Remove unused / legacy resources in `App.xaml`. Specifically the `ControlCornerRadius` override causing the radii in the app to look funky.
Fixes internal bug 39694439
=> [winui2] Remove Unused Resources in `App.xaml`

README.md, WinUIGallery/ControlPages/AnimatedVisualPlayerPage.xaml, WinUIGallery/ControlPages/RichTextBlockPage.xaml, WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/ItemPage.xaml
winui --> windows-app-sdk
also removed en-us from windows + titlebar samples + removed "?view=winui-3.0" from several links
Fixes #987
=> Updated docs URLs

WinUIGallery/ControlPagesSampleCode/SystemBackdrops/SystemBackdropsSample1.txt
Fixed punctuation in SystemBackDropSample1.txt. There was an extra semicolon ";" in the "SetConfigurationSourceTheme()" function definition.
This is a minor change.
Fixes #1041 
No Testing is Needed as this was a change in a text file.
=> Fixed punctuation in SystemBackDropSample1.txt

WinUIGallery/Controls/ControlExample.xaml.cs, WinUIGallery/Helper/ThemeHelper.cs, WinUIGallery/Helper/UIHelper.cs
Use precompiler to branch based on the desired packaging (or non-packaging).
Remove APIs that are not available in unpackaged apps.
Move to standard of if UNPACKAGED (as opposed to if !UNPACKAGED where possible)
as it was confusing looking at both.
Improve support for unpackaged apps.
Improve readability.
Manual build and testing
=> fixes for unpackaged

WinUIGallery/SamplePages/SampleSystemBackdropsWindow.xaml.cs
Add Support MicaAlt Backdrop
more info here
https://docs.microsoft.com/en-us/windows/apps/design/style/mica
=> Add Support MicaAlt

WinUIGallery/ControlPages/WebView2Page.xaml
Add minimum sizes for the WebView 2 samples.
Closes #1037 
=> Add minimum dimensions to WebView 2 sample

WinUIGallery/ControlPages/ListViewPage.xaml, WinUIGallery/ControlPages/ListViewPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/ListView/ListViewSample2_cs.txt, WinUIGallery/ControlPagesSampleCode/ListView/ListViewSample2_xaml.txt
By overriding the ToString method and removing the other header from the UIA header we improve the accessibility.
Fixe #670 
=> Fix a11y issues in listview grouping sample

WinUIGallery/App.xaml.cs, WinUIGallery/Common/ActivityFeedLayout.cs, WinUIGallery/Common/DoubleToThicknessConverter.cs, WinUIGallery/Common/VariedImageSizeLayout.cs, WinUIGallery/ControlPages/BorderPage.xaml.cs, WinUIGallery/ControlPages/CommandBarPage.xaml.cs, WinUIGallery/ControlPages/InputValidationPage.xaml.cs, WinUIGallery/ControlPages/ListViewPage.xaml.cs, WinUIGallery/ControlPages/NavigationViewPage.xaml.cs, WinUIGallery/ControlPages/PullToRefreshPage.xaml.cs, WinUIGallery/ControlPages/RevealFocusPage.xaml.cs, WinUIGallery/ControlPages/RichEditBoxPage.xaml.cs, WinUIGallery/ControlPages/SplitViewPage.xaml.cs, WinUIGallery/ControlPages/StandardUICommandPage.xaml.cs, WinUIGallery/ControlPages/SwipeControlPage.xaml.cs, WinUIGallery/ControlPages/TabViewPage.xaml.cs, WinUIGallery/ControlPages/ThemeTransitionPage.xaml.cs, WinUIGallery/ControlPages/TreeViewPage.xaml.cs, WinUIGallery/Controls/ControlExample.xaml.cs, WinUIGallery/Helper/NavigationHelper.cs, WinUIGallery/Helper/NavigationOrientationHelper.cs, WinUIGallery/Helper/ThemeHelper.cs, WinUIGallery/IdleSynchronizer.cs, WinUIGallery/ItemsPageBase.cs, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/NewControlsPage.xaml.cs, WinUIGallery/SearchResultsPage.xaml.cs, WinUIGallery/SettingsPage.xaml.cs, WinUIGallery/TabViewPages/TabViewWindowingSamplePage.xaml.cs
With the release of 1.2 experimental 1/2, UWP is no longer supported by the WinUI3 platform.
(https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel)
This change removes the compile-time code branches related to UNIVERSAL to improve on code readability, maintainability, and simplicity.
This removes one barrier to comprehension of our source code.
Build/Manual testing
=> Simplify WinUI Gallery Code 

WinUIGallery/Controls/HeaderTile.xaml.cs
Some DependencyProperties have incorrect names in HeaderTile.xaml.cs and I try to correct them.
=> Correct DependencyProperty names in HeaderTile.xaml.cs

WinUIGallery/ControlPages/InfoBarPage.xaml
The option panels were a bit inconsistent and also resized on the options being selected. Now they have a fixed sized and the comboboxes are stretched.
Closes #1002 
=> Update visual design of Infobar sample option panels

WinUIGallery/DataModel/ControlInfoData.json
This change updates the main page to show the correct New and Updated pages.
Prep for 1.3.16 release
=> Update ControlInfo for New and Updated pages

WinUIGallery/ControlPages/ItemsRepeaterPage.xaml
=> Added C# code to the ItemsRepeater page

WinUIGallery/ContentIncludes.props, WinUIGallery/ControlPages/XamlCompInteropPage.xaml, WinUIGallery/ControlPagesSampleCode/Motion/AnimationInterop/AnimationInteropSample2_cs.txt, WinUIGallery/ControlPagesSampleCode/Motion/AnimationInterop/AnimationInteropSample2_xaml.txt
=> Clarified animationInterop sample

WinUIGallery/ControlPages/NavigationViewPage.xaml, WinUIGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample4_cs.txt
- replaced "args.selectedItem" by "args.InvokedItem"
- fixed the introduction text
Fixes #1143
=> Navigation View Fixes

packagestore/readme.md
With the recent changes to nuget.config, I added a directory that can be used to easily test nuget packages locally without having to configure a feed.  That change did assume that the directory existed.  Now it does :)
Thanks for VinJa for pointing this out.
=> add a readme to packagestore to ensure its existence

WinUIGallery/ControlPages/ImplicitTransitionPage.xaml
=> Fixed visual bug on implicit transitions page

WinUIGallery/ControlPages/CommandBarFlyoutPage.xaml.cs, WinUIGallery/ControlPagesSampleCode/CommandBarFlyout/CommandBarFlyoutSample1_cs.txt
The code and the same showing usage were not the same. Updated them to match and improved the comment
=> fix command bar flyout sample text to match the code

WinUIGallery/ControlPages/SliderPage.xaml, WinUIGallery/ControlPages/SliderPage.xaml.cs
=> Showcase SnapsTo property for the Slider control 

WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/ItemPage.xaml, WinUIGallery/Navigation/NavigationRootPage.xaml.cs
This PR solves some unused binding modes that showed us as compiler errors.
=> Resolve compiler errors

WinUIGallery/DataModel/ControlInfoData.json
Updated the black & white navView icons for the "System" and the "Windows" categories. Before this change, they both used the same default icon.
=> Updated icons for System & Windows

WinUIGallery/ControlPages/InfoBadgePage.xaml, WinUIGallery/ControlPages/InfoBadgePage.xaml.cs, WinUIGallery/DataModel/ControlInfoData.json, WinUIGallery/WinUIGallery.DesktopWap.csproj
Added InfoBadge Example
InfoBadge is missing in Samples and winui-gallery
=> Add InfoBadge

WinUIGallery/Controls/DesignGuidance/TypographyControl.xaml, WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/Navigation/NavigationRootPage.xaml
For western languages this is invisible, but in CJK context, these icons break and show "garbled" chinese caracters.
=> fix deprecated icons

WinUIGallery/Common/DeviceFamilyTrigger.cs, WinUIGallery/ControlPages/AcrylicPage.xaml, WinUIGallery/ControlPages/AnimatedVisualPlayerPage.xaml, WinUIGallery/ControlPages/PersonPicturePage.xaml, WinUIGallery/ControlPages/RichTextBlockPage.xaml, WinUIGallery/Controls/ControlExample.xaml, WinUIGallery/Controls/TileGallery.xaml, WinUIGallery/DataModel/ControlInfoData.json
docs.microsoft.com to learn.microsoft.com
Even though docs.ms has the automatic redirect, it's good to stay up to date :)
=> update links to learn.ms.com

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
=> Update issue templates

WinUIGallery/ControlPages/BreadcrumbBarPage.xaml, WinUIGallery/ControlPages/BreadcrumbBarPage.xaml.cs
=> Fix typos in BreadCrumbBarPage sample

WinUIGallery/App.xaml, WinUIGallery/Package.WAP.Dev.appxmanifest, WinUIGallery/Package.WAP.appxmanifest, WinUIGallery/Properties/AssemblyInfo.cs, WinUIGallery/standalone.props
WASDK 1.3 is out! 🎉 Updating WinUI Gallery accordingly.
=> Update to WASDK 1.3 🎉

README.md, WinUIGallery/standalone.props
- Update the WinAppSDK version
- Fix the VS version in the readme
- Fix the install instructions in the readme
=> Update to WinAppSDK 1.3.1

WinUIGallery/Controls/DesignGuidance/ColorSections/BackgroundSection.xaml
Small spelling fix in the color design guidance section
Incorrect spelling
=> Small spelling fix

WinUIGallery/ControlPages/WebView2Page.xaml
The WinUI Website has been taken offline and the sample opens a 404 page. Since this is not ideal, the URL is changed to the WinUI 3 docs.
=> Update URL on WebView 2 sample

UITests/AxeHelper.cs, UITests/SessionManager.cs, UITests/TestBase.cs, WinUIGallery/Controls/PageHeader.xaml, WinUIGallery/WinUIGallery.csproj, azure-pipelines.yml
This PR fixes the build error which is currently blocking CI.
=> Fix build errors and CI

WinUIGallery/ControlPages/AnnotatedScrollBarPage.xaml.cs
Fix division by zero exception when the window is too narrow.
Fixes #1365
=> Fix division by zero

WinUIGallery/ControlPages/ListViewPage.xaml
The brushes used for the messaging sample were out of date which this PR addresses.
=> Update ListView sample code to match used resources

WinUIGallery/ControlPages/InfoBadgePage.xaml
=> Update infobadge samples to be more accessible

WinUIGallery/ControlPages/InfoBadgePage.xaml
This PR fixes issues with the infobadge page which broke the CI
=> Unblock CI by fixing Axe errors

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, README.md
- Add "needs-triage" label to bug and new feature request template
- Add Badges to readme
#1392
=> Add "Needs-Triage" Label

WinUIGallery/ControlPagesSampleCode/System/FilePickerSample1_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample2_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample3_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample4_cs.txt, WinUIGallery/ControlPagesSampleCode/System/FilePickerSample5_cs.txt
Corrects the `FilePicker` sample code modified by #1396.
Run the app and confirmed its content.
=> Fix FilePicker sample code

WinUIGallery/ControlPages/TextBoxPage.xaml
Fixes XAML code missing a '/'.
Fixes #1430
=> Fix TextBox XAML sample code

WinUIGallery/Package.Dev.appxmanifest, WinUIGallery/Package.appxmanifest, WinUIGallery/Properties/AssemblyInfo.cs
Fixes #1440. 
Checked the version info at the SettingsPage.
=> Update version info to v2.3.0

WinUIGallery/Package.Dev.appxmanifest, WinUIGallery/Package.appxmanifest, WinUIGallery/Properties/AssemblyInfo.cs, WinUIGallery/standalone.props
Update WASDK from preview to 1.5 stable 🎉
=> Update to WASDK 1.5 🎉

WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml.cs
There are two major improvements:
- Use separate thread to filter items
- Move away from modifying an observable collection but instead just reassign collection since that updates the UI faster
Closes #1460
=> Update icon search to not freeze app

WinUIGallery/Package.Dev.appxmanifest, WinUIGallery/Package.appxmanifest, WinUIGallery/Properties/AssemblyInfo.cs
=> Update Version to 2.4.1.0

WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml, WinUIGallery/ControlPages/DesignGuidance/IconsPage.xaml.cs
=> Fix issue when searching on icons page with item being selected

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
(same as title)
(no explanation needed)
(I dunno)
(nope)
=> add 23H2 and 24H2 in forms

Directory.Build.props, UITests/README.md
Adjusts one link as part of #1344
=> Update link to point to WinUI 3 docs

README.md
=> Fix landing image

WinUIGallery/Package.Dev.appxmanifest, WinUIGallery/Package.appxmanifest, WinUIGallery/Properties/AssemblyInfo.cs
- Change version number from 2.4.2.1 - #1568  to 2.4.3
- Turns out you can't have a non-zero revision number on Store
=> Update Version 2.4.3

WinUIGallery/ControlPages/WebView2Page.xaml, WinUIGallery/ControlPagesSampleCode/NavigationView/NavigationViewSample5.txt
Simple code cleanup
`mux` not needed in winui3
Manual.
=> Cleanup: Unnecessary xaml namespaces

WinUIGallery/ControlPages/ListViewPage.xaml.cs, WinUIGallery/ControlPages/XamlUICommandPage.xaml, WinUIGallery/ControlPages/XamlUICommandPage.xaml.cs
This PR adds UIA announcements to samples where they were missing. Also cleaning up unused function in XAMLUICommand page
Closes #169 and closes #334
=> Update samples to announce UI changes to narrator

WinUIGallery/ControlPages/MenuFlyoutPage.xaml, WinUIGallery/DataModel/ControlInfoData.json
Add a new sample about `RadioMenuFlyoutItem` in `MenuFlyout` page.
I just happened to come across this class in looking for derived class from `MenuFlyoutItem`.
Manual
=> New sample: RadioMenuFlyoutItem

WinUIGallery/ControlPages/ContentDialogPage.xaml.cs, WinUIGallery/Navigation/NavigationRootPage.xaml, WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/SettingsPage.xaml, WinUIGallery/SettingsPage.xaml.cs, WinUIGallery/Shaders/CaptureHelper.cs, WinUIGallery/Shaders/OverlayPanel.xaml, WinUIGallery/Shaders/PixelShaderRenderer.cs, WinUIGallery/Shaders/RippleFade.cs, WinUIGallery/Shaders/ShaderPanel.xaml.cs, WinUIGallery/Shaders/ShaderSourceHelper.cs, WinUIGallery/Shaders/TwirlDismiss.cs, WinUIGallery/Shaders/Wipe.cs
- Fix DPI issues with TwirlDismiss
- Add ComputeSharp animation combobox to settings page
- Add Wipe effect
- Fix up transparent/black pixels in ripple when sampling outside bounds or on a transparent background
=> Add Wipe effect, fix quality issues with ripple, prep for demo

WinUIGallery/Navigation/NavigationRootPage.xaml.cs, WinUIGallery/Shaders/CaptureHelper.cs, WinUIGallery/Shaders/ShaderPanel.xaml.cs
=> Add a way to save a RenderTargetBitmap to a file

WinUIGallery/SettingsPage.xaml, WinUIGallery/SettingsPage.xaml.cs
Copy "git clone https://github.com/microsoft/WinUI-Gallery" to clipboard when clicked.
This way is easier and less error prone.
Run the app and confirmed that the text is copied to the clipboard.
=> Copy "git clone https..." to clipboard when clicked

WinUIGallery/ControlPages/ContentDialogPage.xaml.cs, WinUIGallery/Shaders/PixelShaderRenderer.cs, WinUIGallery/Shaders/RippleFade.cs, WinUIGallery/Shaders/RippleFadeGenerated.hlsl, WinUIGallery/Shaders/ShaderPanel.xaml, WinUIGallery/Shaders/ShaderPanel.xaml.cs, WinUIGallery/Shaders/Wipe.cs
Update comments, variable names, and add generated shader code for demo script
=> Update comments, variable names, and add generated shader code for demo script

WinUIGallery/ControlPages/ColorPaletteResourcesPage.xaml
Fixes #1674 
**manually tested**
=> Fix: `ColorPaletteResourcesPage` theme toggle highlight

WinUIGallery/Package.Dev.appxmanifest, WinUIGallery/Package.appxmanifest, WinUIGallery/Properties/AssemblyInfo.cs
Update WinUI-Gallery Version to 2.5.1
=> Update Version Info to 2.5.1

WinUIGallery/ControlPages/ScrollViewPage.xaml
This PR will improve spacing on the `ScrollView` sample page. Also, replaced `Margin` properties with `ColumnSpacing`, `RowSpacing` and `Spacing` properties.
The `ScrollView` sample page has some spacing issues. Check the screenshots below.
Ran the app and verified its contents.
Before:
After:
=> Improve spacing on ScrollView sample page

UITests/UITests.csproj
Try unblocking the CI by fixing UITests
=> Unblock UITests in CI

Tools/Get-LatestAddedSamples.ps1, Tools/Get-LatestUpdatedSamples.ps1, WinUIGallery/DataModel/ControlInfoData.json
Resolving the issue referenced in #1727
=> Update the scripts for the most recently added and updated samples

WinUIGallery/Samples/ControlPages/ListViewPage.xaml
Fixed a small XAML error. x2 double quotes.
=> Fixed a small XAML error

WinUIGallery/Pages/ItemPage.xaml.cs
This broke with the reorg of the project structure. Fixes #1750
=> Fix github links button

WinUIGallery/Samples/Data/ControlInfoData.json
Add missing periods to control descriptions for consistency.
Ran the app and checked the changes.
=> Add missing periods to control descriptions

WinUIGallery/Samples/ControlPages/XamlFundamentals/XamlResourcesPage.xaml
Apply rounded corners on the **Xaml fundamentals - Resources** page.
Ran the app and verified the changes.
=> Apply rounded corners

WinUIGallery/Pages/SettingsPage.xaml
This PR updates the copyright year on SettingsPage.xaml.
=> Update year on SettingsPage.xaml

WinUIGallery/Samples/ControlPages/RatingControlPage.xaml, WinUIGallery/Samples/ControlPages/RatingControlPage.xaml.cs
This PR applies minor improvements on the `RatingControl` sample page.
Ran the app and verified the changes.
=> Apply minor improvements on the RatingControl sample page

Tools/Get-LatestAddedSamples.ps1, Tools/Get-LatestUpdatedSamples.ps1
Additional fix for app structure changes
=> Refactor path variable to point to Samples folder in Tools scripts

WinUIGallery/Samples/ControlPages/SelectorBarPage.xaml
Closes #1766.
Ran the app and verified the changes.
=> Fix selected item issue on the SelectorBar control page

WinUIGallery/Samples/Data/ControlInfoData.json
Capitalized some control names in their descriptions.
=> Update control descriptions for consistency

WinUIGallery/Styles/ItemTemplates.xaml
=> [UX] Fix textscaling issues

WinUIGallery/Samples/ControlPages/CaptureElementPreviewPage.xaml.cs
This PR handles the `UnauthorizedAccessException` and displays a dialog to recommend checking the camera access settings.
Fixes #1864.
=> Handling UnauthorizedAccessException on Capture Element / Camera Preview page

WinUIGallery/Samples/ControlPages/HyperlinkButtonPage.xaml
This PR replaces the HTTP URL with HTTPS in the 'HyperlinkButton' sample code.
Improves security and consistency with other links.
=> Replace HTTP URL with HTTPS in the 'HyperlinkButton' sample code

WinUIGallery/Samples/ControlPages/Accessibility/AccessibilityKeyboardPage.xaml, WinUIGallery/Samples/ControlPages/Accessibility/AccessibilityScreenReaderPage.xaml
=> Refined text formatting by adding spaces to improve readability.

WinUIGallery/Samples/ControlPages/Accessibility/AccessibilityColorContrastPage.xaml
looks like a cut and paste issue or incomplete edit was committed previously
Just a typo fix in text displayed within the app.
Improves understanding and makes text clearer.
manually - it's just UI text.
Before:
After:
=> Fix typo in AccessibilityColorContrastPage.xaml

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
Adding issue type to the issue template for keeping track easier.
=> Add bug type to issue templates

WinUIGallery/Pages/SettingsPage.xaml
=> Add the `CsWin32` reference on the Settings page

WinUIGallery/Controls/SampleCodePresenter.xaml.cs
This PR ensures that the code presenter inside the `SampleCodePrenseter` custom control is visible whenever it has code to render.
Fixes #2049.
Manually tested.
=> Ensure presenter visibility in sample rendering
